### ISSUE TITLE
Question: What happens if ingest run crashes

### ISSUE THREAD

**Issue by Mooey28** [tenable/integration-jira-cloud#101]
What happens if the ingest run stops for whatever reason (particular for the first run when trying to ingest everything), and only partial results are exported from Tenable and loaded into Jira?

If the script is restarted, would it potentially create duplicates of what is already loaded in to Jira, or would it read through what's in Jira first and pick up where it left off?

**Comment by SteveMcGrath** [comment]
no, it will always update the issues already in jira

**Comment by Mooey28** [comment]
Thank you for confirming!
