### ISSUE TITLE
Document in Wiki how to use tio_severities

### ISSUE THREAD

**Issue by Bobbo850** [tenable/integration-jira-cloud#104]
We are using Jira Cloud and Tenable.io.  The only vulnerabilities that are being pulled into our Jira are the Critical and High vulnerabilities.  It is not pulling any Medium or Lows in.  Any guidance would be appreciated.

**Comment by SteveMcGrath** [comment]
note the readme for how to adjust the severities in tio using the tio_severities declaration.

**Comment by Bobbo850** [comment]
@SteveMcGrath  Thank you!!!! While yes we probably should have RTFM, this went through three different levels of support at Tenable and they still haven't given us this answer.  Would you consider putting this in the Wiki since we all assumed we had missed a step in our setup and no one at Tenable, our Tenable expert at our reseller,  or at my tech company ever thought to review the readme.txt?
