### ISSUE TITLE
Loop - Status QUEUED

### ISSUE THREAD

**Issue by carlossaito** [tenable/integration-jira-cloud#110]
Hi,
We implemented the script and found that after some data was generated, the script went into a loop.

![image](https://user-images.githubusercontent.com/75276112/116294166-0827cf80-a76e-11eb-88dd-b0e796ce17ba.png)

**Comment by SteveMcGrath** [comment]
looks like the asset export is in a queued state, likely a backup in the IO platform itself.  Typically those are temporary.

**Comment by carlossaito** [comment]
Understand.

but ... how long does this backup take, if it is running?

Because, we have been with this behavior for days.

Do I continue with the execution of the script until the state returns to normal?

**Comment by carlossaito** [comment]
> looks like the asset export is in a queued state, likely a backup in the IO platform itself. Typically those are temporary.
> 
> The behavior of waiting like that is expected.

Understand.

but ... how long does this backup take, if it is running?

Because, we have been with this behavior for days.

Do I continue with the execution of the script until the state returns to normal?

**Comment by SteveMcGrath** [comment]
Exports themselves shouldn't take more than a couple hours.  If your seeing really long export times, then you may want to contact support and let them know that your having a long queue times for there exports.  They'll want to know the export UUID (Noted in the last log item pictured) and the amount of time you have been seeing that export sitting in the queue.  If there is any pushback, then reference this issue.

The core problem isn't related to this integration, so I will note that this is an environment issue with the upstream api.
