### ISSUE TITLE
Vulnerability severity rating for task getting updated multiple times her run?

### ISSUE THREAD

**Issue by dwestness** [tenable/integration-jira-cloud#113]
I have a JIRA alert that notifies me for activity regarding "CRITICAL" vulnerability task tickets and it has been going nuts lately.
I have been attempting to track down root cause since it seems to be related to a specific ticket generated so much noise. I enabled debug logging on the integration to filter down activity related to this to paint a picture for myself, but i am lost as to the behavior.

I can see in the debug logs a lot of activity around this task getting update repeatedly during a single run and the severity level getting updated to "Medium -> Critical -> Medium -> Critical" over and over during the run. Is this something wrong in the code or something wrong in my setup?

Attaching the snippits from my log here to show examples
[tenablejira_severity_issue_logs.txt](https://github.com/tenable/integration-jira-cloud/files/6415008/tenablejira_severity_issue_logs.txt)

**Comment by dwestness** [comment]
For what it's worth, This Tenable Plugin ID does shows as "CRITICAL" in the tenable.io console and always has. It should never have been updated to "MEDIUM"

**Comment by dwestness** [comment]
As i'm continuing to look at this.. It is odd.. In tenable the vulnerability itself is listed as CRITICAL, however half of the assets under the vulnerability itself do show that this plugin id is medium while the others show as critical.

I have no idea how the same vulnerability could have different vulnerability rating depending on the asset itself. So it does appear to be inconsistant in tenable.io somehow.. 

I assumed the integration here would set the TASK vulnerability severity based on that of the plugin itself, but is the behavior to upstream the vulnerability of the task from the sub-task? That may explain the behavior, but still something wrong on the tenable end i imagine perhaps?

**Comment by SteveMcGrath** [comment]
Do you have some of these findings recasted to medium?

**Comment by dwestness** [comment]
There are no recast rules related to this plugin id or assets.
We only have a couple of recast rules for specific plugin ids and take them
down the "Info" that are unrelated to this.

Dan Westness
Information Technology
Systems Administration Team Lead

**Comment by SteveMcGrath** [comment]
Yeah I started looking into the default config to understand what field it's pulling from (as there are a few that could be used for severity) and the default for IO is `plugin.risk_factor` which should not change even if recast or accepted.

https://github.com/tenable/integration-jira-cloud/blob/master/tenable_jira/config.py#L324-L331

**Comment by SteveMcGrath** [comment]
What was the age of the vulnerabilities?  were the newer ones "Critical" and the older ones "Medium"?  What was the approx age of each classification?

**Comment by dwestness** [comment]
Dan Westness
Information Technology
Systems Administration Team Lead

**Comment by dwestness** [comment]
None of them are that old since this google chrome update was just released a couple weeks ago.
No clear divided line between the CRITICAL vs MEDIUM ones

![image](https://user-images.githubusercontent.com/48287057/116928037-841c8e80-ac2a-11eb-861f-8d60cfded838.png)

**Comment by SteveMcGrath** [comment]
At this point, it doesn't seem like an issue with the integration, more the upstream data within Tenable.io.  I would recommend filing a support case with Tenable support.
