### ISSUE TITLE
Any way to pull instance ID vs the fqdn ?

### ISSUE THREAD

**Issue by MichaelTay0** [tenable/integration-jira-cloud#114]
Is it possible for the integration to be able to pull in instance-id info as well?

and have that populated in the asset tab of the vulnerability task

**Comment by SteveMcGrath** [comment]
sure can, just add in the appropriate sections of the config

https://github.com/tenable/integration-jira-cloud/issues/81#issuecomment-724799379

**Comment by MichaelTay0** [comment]
Does tenable allow for adding aws account id, instance name and tags to the ticket
