### ISSUE TITLE
Python script and modules to retrieve problem list and print Jira Cloud screen

### ISSUE THREAD

**Issue by javijor80** [tenable/integration-jira-cloud#115]
Hi SteveMcGrath,

Could you please confirm if this python script is complete and from which url we can get all the modules used in the import such as jira, base_config, etc.?

from tenable_jira.jira import Jira
from tenable_jira.config import base_config
from restfly.utils import dict_merge
import yaml, json

config_file = 'config.yaml'

config = dict_merge(
base_config(),
yaml.load(open(config_file), Loader=yaml.Loader)
)
jira = Jira(
'https://{}/rest/api/3'.format(config['jira']['address']),
config['jira']['api_username'],
config['jira']['api_token']
)
print('Available Issue Types are:')
for a in jira.issue_types.list():
print('{:>10}: {}'.format(a.get('id'), a.get('name')))

Thanks

**Comment by SteveMcGrath** [comment]
As an FYI, more recent changes to their API should make understanding exactly what issue types are needed: https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-projects/#api-rest-api-3-project-projectidorkey-get

This is related to #111
