### ISSUE TITLE
Ignore IP when creating issues?

### ISSUE THREAD

**Issue by Bobbo850** [tenable/integration-jira-cloud#117]
Is there a way to ignore IP's when creating issues?  We have an environment where a device can have the IP change frequently and its creating a lot of duplicate issues.  We've tried to close them in Jira but then the integration just reopens them.

**Comment by SteveMcGrath** [comment]
is this in SC, or IO?

**Comment by Bobbo850** [comment]
IO

**Comment by SteveMcGrath** [comment]
try making the following change in the config and see if this helps:

https://github.com/tenable/integration-jira-cloud/issues/102#issuecomment-789163169

Also note before you do this, you may want to close the duplicates.

**Comment by Bobbo850** [comment]
Sorry for the delayed response.  I completely deleted all the end point tickets and allowed the integration to occur to create all new tickets with the configuration changes suggested in the linked ticket. Unfortunately, it is still creating duplicates since they have different IPs.   Can you please provide additional guidance.

![image](https://user-images.githubusercontent.com/79342675/120502987-e505c680-c390-11eb-839f-625a90fdbf45.png)

**Comment by SteveMcGrath** [comment]
With that search criteria setup, it should only create duplicates if you have issues in one of the "done" states.  It's not using the IP at all for searching.  Can you please run the integration with the `--troubleshoot` flag?
