### ISSUE TITLE
Recast Severity Not Transferred to Jira

### ISSUE THREAD

**Issue by cc-vy** [tenable/integration-jira-cloud#121]
I am only picking up Criticals and Highs.  When I recast a "Medium" to a "High" in io, the connector picks it up correctly and opens a Jira ticket, but it sets the vulnerability severity field to the original rating, not the recast one.  Is that on purpose?

**Comment by SteveMcGrath** [comment]
It is picking up the original setting, not the recast one.  If you would like to add the finding severity rating, it would have to be a separate field.
