### ISSUE TITLE
Does tenable allow for adding aws account id, instance name and tags to the ticket

### ISSUE THREAD

**Issue by MichaelTay0** [tenable/integration-jira-cloud#123]

**Comment by SteveMcGrath** [comment]
Check this out:

https://github.com/tenable/integration-jira-cloud/issues/81#issuecomment-724799379

**Comment by MichaelTay0** [comment]
Hi Steve,  so are you saying I need to add additional fields to the tabs: - Asset: within my config file?

Or do I need to create a new issue type? 

I am a little confused. 
Here is a snippet of my config file 

The fields we want to be shown in the Asset Tab are 
- aws account id
- was instance name
- aws tags

`tenable:
  access_key: [REMOVED]
  secret_key: [REMOVED]
  tio_ignore_accepted: true
  tio_autoclose_accepted: true
  tio_asset_attr_cache:
    - agent_uuid
    - bios_uuid
    - aws_ec2_instance_group_name
    - aws_ec2_name
  tio_severities:
    - low
    - medium
    - high
    - critical

screen:
  jira_ids:
    - 11850
    - 11851
  tabs:
    Asset:
      - Tenable Asset UUID
      - Tenable Asset Tags
      - Tenable Platform
      - AWS Instance Group Name
      - AWS Name
      - Device Hostname
      - Device NetBIOS Name
      - Device DNS Name
      - Device IPv4 Addresses
      - Device IPv6 Addresses
      - Device MAC Addresses
      - Device Network ID
      - Vulnerability Repository ID
      - Vulnerability Repository Name
      - AWS Instance ID
      - Network Tag

jira:
  api_token: [REMOVED]
  api_username: michael.tayo@tempus.com
  address: [REMOVED]

project:
  key: TENB
  leadAccountId: [REMOVED]
`

**Comment by SteveMcGrath** [comment]
that would be correct.  Your basically extending the asset tab schema
