### ISSUE TITLE
JIRA Cloud - script cannot find \'VULN\' value

### ISSUE THREAD

**Issue by EugeneKor** [tenable/integration-jira-cloud#124]
Ran the script. Script successfully created the Vuln Management project in JIRA Cloud but would not pull in any findings.

Below is the last entry from the logfile

> 2021-06-14 15:07:46,418 restfly.errors.BadRequestError ERROR [400: POST] https://cloudbeds.atlassian.net/rest/api/3/search body=b'{"errorMessages":["The value \'VULN\' does not exist for the field \'project\'."],"warningMessages":[]}'

**Comment by SteveMcGrath** [comment]
This looks like this could be a permissions issue.  can you check to see that your permissions for the user you are running the script as has all of the required permissions mentioned in the readme?
