### ISSUE TITLE
How to use RUN_EVERY option to get the vulnerabilities into JIRA automatically

### ISSUE THREAD

**Issue by kalpana80** [tenable/integration-jira-cloud#125]
I have integrated JIRA cloud with Tenable.io for getting the vulnerabilities into JIRA. But the vulnerabilities flow into JIRA only when we manually run the script. How do i use the RUN_EVERY option to get the results flowing into JIRA cloud automatically.

**Comment by kalpana80** [comment]
Any update?

**Comment by SteveMcGrath** [comment]
RUN_EVERY simply specifies the number of hours between runs.  This assumes that the integration will be run as a persistent service, and not on a cron schedule.  No the that RUN_EVERY also can be specified int he config using the service declaration:

https://github.com/tenable/integration-jira-cloud/blob/master/example_config_file.yaml#L35-L41
