### ISSUE TITLE
Tenable IO integration with JIRA cloud shows error "restfly.errors.ServerError ERROR [500: POST]"

### ISSUE THREAD

**Issue by kalpana80** [tenable/integration-jira-cloud#126]
Tenable.io integration with JIRA cloud shows error "restfly.errors.ServerError ERROR [500: POST] 

Every time we run the command , the execution stops with following error: restfly.errors.ServerError ERROR [500: POST] https://monotype.atlassian.net/rest/api/3/search body=b'<!DOCTYPE html>\n<html>\n <head>\n <meta

**Comment by SteveMcGrath** [comment]
updates?
