### ISSUE TITLE
Limiting custom field

### ISSUE THREAD

**Issue by pappsec20** [tenable/integration-jira-cloud#127]
Is there any way to limit custom field which will be created on Jira after using the plugin?

**Comment by SteveMcGrath** [comment]
The integration will only create the fields that it uses.  I don't understand the question.

**Comment by pappsec20** [comment]
For example if I don't want Vulnerability Port,Vulnerability Protocol,Vulnerability Repository ID etc to be imported to Jira..is there any way to restrict that?

**Comment by SteveMcGrath** [comment]
currently no, and removing those specifically would break how sub-tasks, or Vuln findings are found.
