### ISSUE TITLE
"Only Jira administrators can manage screens"

### ISSUE THREAD

**Issue by justilawson** [tenable/integration-jira-cloud#129]
I have everything set up, I ran under my permissions (Jira admin). When I run the script by hand it connects and works perfectly. I want to switch over to using a project admin and their API key. When I run the script I get an error:

 [403: GET] https://mycompany/rest/api/3/screens?startAt=-100&maxResults=100 body=b'{"errorMessages":["Only Jira administrators can manage screens."],"errors":{}}'

I have validated the project admin has all the below permissions:
Assignable User
Assign Issues
Close Issues
Create Issues
Delete Issues
Edit Issues
Link Issues
Modify Reporter
Move Issues
Resolve Issues
Schedule Issues
Set Issue Security
Transition Issues

**Comment by SteveMcGrath** [comment]
you will likely need to manually code int he screen ids instead of letting the script figure them out.  You will need to add the following lines into your config:

```yaml
screen:
    jira_ids:
    - 18802
    - 18803
```

Simply replace the IDs with the relevent IDs within your own instance.

**Comment by justilawson** [comment]
updated config with the screen jira_ids from our instance and now receive this error...

restfly.errors.UnauthorizedError ERROR [401: GET] https://mycompany.atlassian.net/rest/api/3/screens/11610/tabs body=b'{"errorMessages":[],"errors":{}}

**Comment by SteveMcGrath** [comment]
that looks like a permission error.  Can you run with `--setup-only` and then use the generated config with the project admin keys?

**Comment by FvS-VT** [comment]
Hey @SteveMcGrath,
we are currently experiencing the exact same issue that @justilawson had, so it's pity this issue does not have a closure - just your suggestion for a run with --setup-only. 

Our Jira administrators gave the user, in whose context the script runs, all the suggested rights. However the Jira API GET call for the tabs of one of the 2 project screens keeps failing, unless we make the user Site Admin or Trusted. Once we set it to be just a Basic user, the script is failing.

Tomorrow we will try a run with --setup-only, as you suggested back in 2021. I was asking myself what you mean by writing "with the project admin keys". Could you please give an example? Do you mean:
jira: 
&nbsp;&nbsp;key: VULN

**Comment by SteveMcGrath** [comment]
Jira has multiple "Admins". Site admin, project admin, etc. Also worth noting that some settings can be overloaded unless explicitly stated, so ensure that the account not only has admin access, but also explicitly has all the permissions defined in the OP.

**Comment by FvS-VT** [comment]
Hi,

thanks for the fast reply and support.
I found it not logical that even GET calls against the Jira API's screens resource (/rest/api/3/screens) already require an admin user context, but hey, it is Jira.
