### ISSUE TITLE
The newly created project is Slow and Lagging

### ISSUE THREAD

**Issue by RG-Martin-I** [tenable/integration-jira-cloud#130]
Hey!

I implemented this completely by myself as the Tenable support was completely useless.
I was just wondering if maybe i am doing something wrong because i created a few Projects with this script to test it out and all of them were laggy and slow, i don't experience the same issues for other projects that we have only for this one created from the script.
Upon testing i would delete the project and create a new one to test, so there aren't more than one projects managed by the script.
Current open tickets in the project are around 400.

[example.txt](https://github.com/tenable/integration-jira-cloud/files/6905193/example.txt)

I removed anything that is sensitive in this config file.

<img width="741" alt="Screenshot 2021-07-30 at 8 06 20" src="https://user-images.githubusercontent.com/88177659/127603379-cb9dc788-9464-41f6-9d86-2a7b87d536be.png">

Thank you in advance and have a nice day! =)

**Comment by SteveMcGrath** [comment]
TBH, there isn't anything that the script is doing that should impact Jira itself, aside from he volume of tickets that it creates and the length of time needed to create them because of how state tracking has to happen.

Once the script is complete, Jira should be able to run without any impact whatsoever.

Are you running this in jira cloud?

**Comment by RG-Martin-I** [comment]
I know it's really strange i don't want to blame the script but every other project behaves alright,
and just to mention i am not trying to browse the project while the script is working, i still run it manually to test it out.

And sorry i forgot to mention but yes, this is Jira Cloud.

**Comment by SteveMcGrath** [comment]
Have you contacted Atlassian?
