### ISSUE TITLE
FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by Squazzle** [tenable/integration-jira-cloud#132]
Hello!

I've installed the integration, with no issues. However, when I try to upload the config file I receive the following error:

File "c:\users\Username\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\path\\to\\logfile.log'

**Comment by SteveMcGrath** [comment]
Did you specify a logfile in your config?  can you please post a sanitized version of your configfile?

**Comment by Squazzle** [comment]
Hi Steve, please disregard! I realize now at the end of the config I had not deleted out the sample text.
