### ISSUE TITLE
Could not find a version that satisfies the requirement integration-jira-cloud

### ISSUE THREAD

**Issue by sreliasanderson** [tenable/integration-jira-cloud#133]
Hey,

The operating system I'm working on is CentOS, but when I try to install the program, the following message is displayed:
ERROR: Could not find a version that satisfies the requirement integration-jira-cloud (from versions: none)
ERROR: No matching distribution found for integration-jira-cloud.

Can you help me ?
What can I do to fix the problem?

**Comment by SteveMcGrath** [comment]
Please note that it will not work on python < 3.6.  Check to see if the version your running is current `python --version`

**Comment by sreliasanderson** [comment]
I have two versions installed:
[admin @ core ~] $ python --version
Python 2.7.5
[admin @ core ~] $ python3 - version
Python 3.6.8
But when running the atepa integration setup, I'm following FirsRun using pip3.

**Comment by SteveMcGrath** [comment]
are you asking for the correct package?

```bash
pip3 install tenable-jira-cloud
```

**Comment by SteveMcGrath** [comment]
```bash
pip3 uninstall tenable-jira-cloud && pip3 install tenable-jira-cloud
```

**Comment by sreliasanderson** [comment]
Hi,

I got result running the following command:
/usr/bin/python3 -m pip install --upgrade pip
pip3 uninstall tenable-jira-cloud && pip3 install tenable-jira-cloud

Now I can run the command: tenable-jira ~/path to file/config.yaml

THX
