### ISSUE TITLE
Create separate projects for different tags

### ISSUE THREAD

**Issue by Squazzle** [tenable/integration-jira-cloud#135]
Hello!

Is there a way to create separate Jira projects for different asset groups while using the same Jira API User/API Key and Tenable Keys? 

I want to have a separate Jira project per environment (servers, laptops, etc.) to reflect the different asset groups I have in Tenable. That way its easier for the end-users to see their vulnerability data. Would I have to change something in the provided script to reference a different project or would I just need to recreate everything for each environment?

Thanks!

**Comment by SteveMcGrath** [comment]
you would have to run the script against different config files.  1 config per project
