### ISSUE TITLE
You must specify a valid project lead

### ISSUE THREAD

**Issue by HouseDamage** [tenable/integration-jira-cloud#137]
Hi,

Getting the following errors when trying to run the config.yaml

```
2021-08-12 13:42:24,992 restfly.errors.NotFoundError ERROR [404: GET] https://<redacted>.atlassian.net/rest/api/3/project/VULN body=b'{"errorMessages":["No project could be found with key \'VULN\'."],"errors":{}}'

2021-08-12 13:42:25,119 restfly.errors.BadRequestError ERROR [400: POST] https://<redacted>.atlassian.net/rest/api/3/project body=b'{"errorMessages":[],"errors":{"projectLead":"You must specify a valid project lead."}}'
```

Things I've tried:
- Changing the account id to not include the @email.com part.
- Using the account email as leadaccountId (Changed project lead to 'lead:' also)

I've ensured that the account is a site admin, and I've taken the projectleadID from the profile page of the account in question. I can see the API token activity updates when running the script, so that shouldn't be the issue.

Many thanks!

**Comment by SteveMcGrath** [comment]
You may wasn't to refer to the following link:

https://github.com/tenable/integration-jira-cloud/issues/11#issuecomment-587579360

In short, Jira expects an ID as is specified in that URI

```yaml
project:
  leadAccountId: LEAD_ID_GOES_HERE
```

**Comment by HouseDamage** [comment]
> You may wasn't to refer to the following link:
> 
> [#11 (comment)](https://github.com/tenable/integration-jira-cloud/issues/11#issuecomment-587579360)
> 
> In short, Jira expects an ID as is specified in that URI
> 
> ```yaml
> project:
>   leadAccountId: LEAD_ID_GOES_HERE
> ```

Going to People > then the user showed a slightly different ID which worked. Thanks!

https://github.com/tenable/integration-jira-cloud/issues/11#issuecomment-587614499
