### ISSUE TITLE
jira subtask / tasks

### ISSUE THREAD

**Issue by tsideras** [tenable/integration-jira-cloud#142]
After I upgraded to 1.2.0 from 1.1.23, subtask and tasks are no longer created in jira. It now creates stories with subtasks. There are now tickets 1:1 for vulnerability/asset. Compared to before, each vulnerabilities had all affected assets as subtasks. Another issue that came with with the upgrade, there are story tickets for a vulnerability but no assets listed as affected.

**Comment by SteveMcGrath** [comment]
can you please paste a debug log using the `--troubleshoot` flag?

**Comment by tsideras** [comment]
Steve - Do you have a tenable email I can send the log to? I don't want to past the log file here as it contains hostnames and vulnerabilities.

**Comment by SteveMcGrath** [comment]
smcgrath _at_ tenable.com

**Comment by fredrikjanson** [comment]
Any news on this issue? I believe we are seeing the same, i.e. 1:1 tasks created for Vulnerabilities and sub-tasks. For instance we have about 200 Vulnerability tasks AND 200 Vulnerable Host sub-tasks for Tenable Plugin ID 70544 when it should have been just one Task with 200 sub-tasks

**Comment by SteveMcGrath** [comment]
I never received an email with the details, sorry.  Please resend

**Comment by rbernsteinIIC** [comment]
I am having the same problem.  Was this ever resolved?  All of our tasks (vulnerabilities) only have one subtask.  I found this note in config.py.  Is this now the intended functionality?
# This section defines the issue-types & how to search them.  There should only
# ever be a singular "standard" and no more than 1 "subtask".  The issue-type
# name is what will be used throughout the rest of the config file to determine
# what issue-type gets what data fields.
