### ISSUE TITLE
only critical being imported.  highs are erroring

### ISSUE THREAD

**Issue by mdhedman** [tenable/integration-jira-cloud#143]
We have a basic setup of this.  API key is working as we are getting critical items imported, and the tio_severities is set to critical and high.  

Here is the first part:  
2021-09-27 18:59:03,114 tenable_jira.jira.Jira DEBUG Request:
{
	"method": "POST",
	"url": "https://<JIRA_CLOUD_HOST>/rest/api/3/issue",
	"params": {
		"update_history": false
	},
	"body": {
		"fields": {
			"project": {
				"key": "VULN"
			},
			"issuetype": {
				"id": 3
			},
			"customfield_12409": "1000062",
			"customfield_12410": "N/A",
			"customfield_12411": "AS24-U2-000020 - The Apache web server must perform server-side session management - session_module",
			"customfield_12412": "High",
			"summary": "[1000062] AS24-U2-000020 - The Apache web server must perform server-side session management - session_module",
			"description": {
				"version": 1,
				"type": "doc",
				"content": [
					{
						"type": "heading",
						"attrs": {
							"level": 1
						},
						"content": [
							{
								"type": "text",
								"text": "Description"
							}
						]
					},
					{
						"type": "paragraph",
						"content": [
							{
								"type": "text",
								"text": ""
							}
						]
					},
					{
						"type": "heading",
						"attrs": {
							"level": 1
						},
						"content": [
							{
								"type": "text",
								"text": "Solution"
							}
						]
					},
					{
						"type": "paragraph",
						"content": [
							{
								"type": "text",
								"text": ""
							}
						]
					}
				]
			}
		}
	}
}

And the second part of the error:
Traceback (most recent call last):
  File "/home/admin/tenable-jira/lib64/python3.6/site-packages/tenable_jira/cli.py", line 153, in cli
    ingest.ingest(int(observed_since), first_discovery)
  File "/home/admin/tenable-jira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 743, in ingest
    self.create_issues(vulns)
  File "/home/admin/tenable-jira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 521, in create_issues
    self._process_open_vuln(v, fid)
  File "/home/admin/tenable-jira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 404, in _process_open_vuln
    sys.exit(2)
SystemExit: 2

It's returning with a 400

When we import the Criticals, we get a 200 return.

**Comment by SteveMcGrath** [comment]
Can you please update with the output from a run with the `--troubleshoot` flag?

**Comment by argrithmag** [comment]
Here you go:
[issue_debug.md](https://github.com/tenable/integration-jira-cloud/files/7246410/issue_debug.md)

**Comment by mdhedman** [comment]
I got logged into my other account.  that issue_debug.md is mine

**Comment by mdhedman** [comment]
From my developer:

it is trying to create a new issue for a high finding (the apache) one, but that fails
so it never creates the specific host sub-tasks

**Comment by SteveMcGrath** [comment]
Can you remove compliance checks from the query?

**Comment by mdhedman** [comment]
We're not sure how to do that.  looking at our query in Tenable and we don't see any option either way.

**Comment by sthompson-hypori** [comment]
I work with @mdhedman and have traced this down to a failed restfly _req call with the following kwargs that are passed into it.  Everything _looks_ ok with the data, but that REST API call is failing:
`{'params': {'update_history': False}, 'json': {'fields': {'project': {'key': 'VULN'}, 'issuetype': {'id': 3}, 'customfield_12409': '1000062', 'customfield_12410': 'N/A', 'customfield_12411': 'AS24-U2-000020 - The Apache web server must perform server-side session management - session_module', 'customfield_12412': 'High', 'summary': '[1000062] AS24-U2-000020 - The Apache web server must perform server-side session management - session_module', 'description': {'version': 1, 'type': 'doc', 'content': [{'type': 'heading', 'attrs': {'level': 1}, 'content': [{'type': 'text', 'text': 'Description'}]}, {'type': 'paragraph', 'content': [{'type': 'text', 'text': ''}]}, {'type': 'heading', 'attrs': {'level': 1}, 'content': [{'type': 'text', 'text': 'Solution'}]}, {'type': 'paragraph', 'content': [{'type': 'text', 'text': ''}]}]}}}, 'verify': True}`

I am just not sure why Atlassian is rejecting it with a 400.

**Comment by SteveMcGrath** [comment]
The error in question:

```
2021-09-28 18:02:59,201 restfly.errors.BadRequestError ERROR [400: POST] https://<JIRA_CLOUD_HOST>/rest/api/3/issue?update_history=False body=b'{"errorMessages":["We can\'t create this issue for you right now, it could be due to unsupported content you\'ve entered into one or more of the issue fields. If this situation persists, contact your administrator as they\'ll be able to access more specific information in the log file."],"errors":{}}'
```

Is about as verbose as Atlassian gets in this regard.  You may consider updating to 1.2.1 and see if the issue noted from empty paragraph strings may be the culprit.

In either case, this integration was never tested against compliance data.

**Comment by sthompson-hypori** [comment]
@SteveMcGrath thanks!  That actually worked quite well.  I upgraded from 1.2.0 to 1.2.1 and now it is feeding tickets into our system.  I did have to add a custom field to the create and edit screens, but otherwise the insert flow is working.

Thanks again for your help!

**Comment by mdhedman** [comment]
+1 thanks for the support!
