### ISSUE TITLE
Inconsistent Severities in Vulnerability Severity field vs Plugin Rating

### ISSUE THREAD

**Issue by cc-vy** [tenable/integration-jira-cloud#145]
Aside from not being able to handle recasts (is this hopefully going to be added soon?), I am confused about what this is doing in terms of severity ratings. 

I have started seeing some Medium tickets even though I am only set to look for High and Critical.  

For example,  I am looking at plugin 42873,  which is marked as a "high" in the tenable plugins lookup.  In the portal is shows as a High also, but with a VPR of 4.4. 

It is getting picked up by the connector , presumably because it is a high,  but marked as a medium in the Vulnerability Severity field of the ticket.

Tenable VPR Score
4.4
CVSSv2 Base Score
5.0
CVSSv2 Temporal Score
None
CVSSv3 Base Score
7.5
CVSSv3 Temporal Score
None
Tenable Plugin ID
42873
Tenable Plugin Family
General
Tenable Plugin Name
SSL Medium Strength Cipher Suites Supported (SWEET32)
Vulnerability Severity
Medium

Plugin 150355 is another example.  It does not seem to be using the same criteria for importing the vulnerabilities as it is for marking the vulnerability severity field (which i think is also the case on recasts.)

**Comment by SteveMcGrath** [comment]
CVSSv3 base score is 7.5, which would make it a high. Tenable.io uses the CVSS base scores as the basis for severity ranking.

**Comment by SteveMcGrath** [comment]
1.2.1 released with sev pro changes
