### ISSUE TITLE
Disable Auto Severity to Jira Priority 

### ISSUE THREAD

**Issue by cc-vy** [tenable/integration-jira-cloud#146]
I see this in the Change Log:
    Severity Prioritization is now enabled by default
Does that mean that is sets the priority in Jira based on the new Finding Severity by default?  If so, how do I disable that?  I would like to be able to manually adjust by ticket without it setting it back on its own on each run.

**Comment by SteveMcGrath** [comment]
1.2.2 support this.  you just need to set the sevprio to "no" like so:

```yaml
tenable:
  severity_prioritization: no
```

Also worth noting that the debug log will now report the sevprio status at the beginning of the run.
