### ISSUE TITLE
Missing Description and Solution values

### ISSUE THREAD

**Issue by sthompson-hypori** [tenable/integration-jira-cloud#150]
I am not sure if this is specific to our Tenable install or if it is something about our specific version.

Recently the Description and Solution values in the created Jira tickets have been empty.

I traced it down that the vuln JSON object actually has an empty description and solution fields.

We are running Tenable.sc 5.18.0

Is this something that others have seen?

I have spent some time with the transform.py script and came up with some code that will extract the description and solution from the pythonText JSON value - but I do not want to submit a PR if it only impacts our install.

**Comment by SteveMcGrath** [comment]
Feel free to submit a PR and link it to this issue.  I'll happily review && test if it looks like it could assist others as well.
