### ISSUE TITLE
Critical Priority Invalid - BadRequestError ERROR (HTTP 400)

### ISSUE THREAD

**Issue by bobby-mack** [tenable/integration-jira-cloud#153]
**Issue**
Critical vulns will not POST to Jira Vulnerability Management project, with an HTTP 400 (Bad Request) error cited. As a result, the rest of the import job fails for any additional vulns. This issue looks to be isolated to just "critical" severity for the "customfield_11126" field mapping, as the low, medium, and high vulns will POST OK without any issues.

**POST Example**:
_2021-11-29 15:04:11,884 tenable_jira.jira.Jira DEBUG Request: {"method": "POST", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/issue", "params": {"update_history": false}, "body": {"fields": {"project": {"key": "VULN"}, "issuetype": {"id": 10002}, "customfield_11118": "10.0", "customfield_11120": "10.0", "customfield_11123": "144951", "customfield_11124": "Windows", "customfield_11125": "Microsoft Windows 10 Version 1809 Unsupported Version Detection", "priority": {"id": "1"}, "customfield_11126": "Critical", "summary": "[144951] Microsoft Windows 10 Version 1809 Unsupported Version Detection", "description": {"version": 1, "type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Description"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Microsoft Windows 10 version 1809 is running on the remote host.\nMicrosoft ended support for Windows 10 version 1809 Home/Pro on November 10, 2020 and ends for Windows 10 version 1809 Enterprise/Educational on May 11, 2021.\n\nLack of support implies that no new security patches for the product will be released by the vendor. As a result, it is likely to contain security vulnerabilities. Furthermore, Microsoft is unlikely to investigate or acknowledge reports of vulnerabilities. "}]}, {"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Solution"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Upgrade to a version of Microsoft Windows that is currently supported. "}]}]}}}}
2021-11-29 15:04:12,060 urllib3.connectionpool DEBUG https://<JIRA_CLOUD_HOST>:443 "POST /rest/api/3/issue?update_history=False HTTP/1.1" 400 None_

**Troubleshooting**:
Various attempts at running the Jira import will fail at any of the critical vulns regardless of whether the "tio_severities" or "tio_tags" sections are added to the tenable section. I played around with the severity order as well and it didn't make any difference in this case.

**Error with Debug Output**: 
2021-11-29 15:04:12,065 restfly.errors.BadRequestError ERROR [400: POST] https://<JIRA_CLOUD_HOST>/rest/api/3/issue?update_history=False body=b'{"errorMessages":[],"errors":{"priority":"The priority selected is invalid."}}'
2021-11-29 15:04:12,065 root ERROR Caught the following Exception
Traceback (most recent call last):
  File "/opt/tenable4jira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 407, in _process_open_vuln
    i = self._jira.issues.upsert(fields=issue, jql=' and '.join(jql))
  File "/opt/tenable4jira/lib64/python3.6/site-packages/tenable_jira/jira/issues.py", line 48, in upsert
    issue = self.create(**kwargs)
  File "/opt/tenable4jira/lib64/python3.6/site-packages/tenable_jira/jira/issues.py", line 20, in create
    json=kwargs
  File "/opt/tenable4jira/lib64/python3.6/site-packages/restfly/session.py", line 631, in post
    return self._req('POST', path, **kwargs)
  File "/opt/tenable4jira/lib64/python3.6/site-packages/restfly/session.py", line 559, in _req
    raise error_resp
restfly.errors.BadRequestError: [400: POST] https://<JIRA_CLOUD_HOST>/rest/api/3/issue?update_history=False body=b'{"errorMessages":[],"errors":{"priority":"The priority selected is invalid."}}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/tenable4jira/lib64/python3.6/site-packages/tenable_jira/cli.py", line 156, in cli
    ingest.ingest(int(observed_since), first_discovery)
  File "/opt/tenable4jira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 679, in ingest
    self.create_issues(vulns)
  File "/opt/tenable4jira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 527, in create_issues
    self._process_open_vuln(v, fid)
  File "/opt/tenable4jira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 410, in _process_open_vuln
    sys.exit(2)
SystemExit: 2

See attached for full troubleshooting debug markdown file attached (running the job with --troubleshooting).
[issue_debug.md](https://github.com/tenable/integration-jira-cloud/files/7619121/issue_debug.md)

**Comment by SteveMcGrath** [comment]
Looks like the issue is on the jira end and may be due to an improper priority selection when transforming the severities to the appropriate Jira priorities.

The default mapping is here:

```yaml
tenable:
  severity_prioritization:
    critical: 1
    high: 2
    medium: 3
    low: 4
```

You may need to update your config with what works for you.

**Comment by bobby-mack** [comment]
Thanks for following up quickly! We determined that the "critical" priority did not exist previously... and so we created it, but the ID didn't match what is expected in the POST request. As a result, we modified the mapping in the config file to match... in this case 10002.

_[
  {
    "self": "https://redactedcorp.atlassian.net/rest/api/2/priority/10002",
    "statusColor": "#8b0000",
    "description": "",
    "iconUrl": "https://redactedcorp.atlassian.net/images/icons/priorities/critical.svg",
    "name": "Critical",
    "id": "10002"
  },
  {
    "self": "https://redactedcorp.atlassian.net/rest/api/2/priority/2",
    "statusColor": "#ff0000",
    "description": "Serious problem that could block progress.",
    "iconUrl": "https://redactedcorp.atlassian.net/images/icons/priorities/high.svg",
    "name": "High",
    "id": "2"
  },
  {
    "self": "https://redactedcorp.atlassian.net/rest/api/2/priority/3",
    "statusColor": "#f79232",
    "description": "Has the potential to affect progress.",
    "iconUrl": "https://redactedcorp.atlassian.net/images/icons/priorities/medium.svg",
    "name": "Medium",
    "id": "3"
  },
  {
    "self": "https://redactedcorp.atlassian.net/rest/api/2/priority/4",
    "statusColor": "#707070",
    "description": "Minor problem or easily worked around.",
    "iconUrl": "https://redactedcorp.atlassian.net/images/icons/priorities/low.svg",
    "name": "Low",
    "id": "4"
  },_
  
  Everything now works as intended!
