### ISSUE TITLE
tenable-jira: command not found

### ISSUE THREAD

**Issue by looi963** [tenable/integration-jira-cloud#161]
Hi Everyone,

I am new to this. I followed the guide from [https://github.com/tenable/integration-jira-cloud/wiki/FirstRun](url)

But I getting the error tenable-jira not found. Can anyone guide me what is this step about and what I need to config?
<img width="302" alt="Screenshot 2022-02-03 at 11 06 05 PM" src="https://user-images.githubusercontent.com/98965084/152369456-318a1779-bcf5-4a6b-94e1-12e5ca73b4e1.png">

**Comment by SteveMcGrath** [comment]
what was the prior command and output?

**Comment by looi963** [comment]
Hi Steve, 
It was resolved while I created the python virtual environment. So Am I right to say that this command wont worked without python virtual environment?

**Comment by dnoach** [comment]
I believe you have to use pyenv
