### ISSUE TITLE
Tickets are not generated for issues on Jira Cloud

### ISSUE THREAD

**Issue by dnoach** [tenable/integration-jira-cloud#162]
I am attaching the debug file. 
[issue_debug.md](https://github.com/tenable/integration-jira-cloud/files/8016328/issue_debug.md)

**Comment by SteveMcGrath** [comment]
Looks like the root cause is too many concurrent jobs running.  The .io platform won't allow to many concurrent exports.  Are you running this as a dedicated user?

```
restfly.errors.TooManyRequestsError: [429: POST] https://cloud.tenable.com/vulns/export body=b'{"values":["739c3381-142d-4012-a7b3-71b7bff9abce","673889fa-9957-4a2e-b708-50ad299d5fa9"],"strings":["Duplicate export (job_uuid="," container_uuid=","). not allowed. Please modify request or wait until existing export is complete."],"empty":false,"value_count":2,"bytes":"RHVwbGljYXRlIGV4cG9ydCAoam9iX3V1aWQ9NzM5YzMzODEtMTQyZC00MDEyLWE3YjMtNzFiN2JmZjlhYmNlIGNvbnRhaW5lcl91dWlkPTY3Mzg4OWZhLTk5NTctNGEyZS1iNzA4LTUwYWQyOTlkNWZhOSkuIG5vdCBhbGxvd2VkLiBQbGVhc2UgbW9kaWZ5IHJlcXVlc3Qgb3Igd2FpdCB1bnRpbCBleGlzdGluZyBleHBvcnQgaXMgY29tcGxldGUu"}'
```

**Comment by dnoach** [comment]
I am running as a dedicated user. I might have initiated multiple times the export while trying to get things right. How can I terminate all jobs?

**Comment by dnoach** [comment]
Ok looks like that was it, I was just running this too many times in parallel. The error cleared out. I need to work around the permissions issues now.

**Comment by dnoach** [comment]
Now seeing these errors, but my API user is admin so not sure why will have issue setting these fields:

`2022-02-09 09:06:46,828 restfly.errors.BadRequestError ERROR [400: POST] https://<JIRA_CLOUD_HOST>/rest/api/3/issue?update_history=False body=b'{"errorMessages":[],"errors":{"customfield_11623":"Field \'customfield_11623\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_11625":"Field \'customfield_11625\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_11624":"Field \'customfield_11624\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_11626":"Field \'customfield_11626\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_11618":"Field \'customfield_11618\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_11620":"Field \'customfield_11620\' cannot be set. It is not on the appropriate screen, or unknown."}}'`

**Comment by dnoach** [comment]
can close the issue was I had to link the screens in the config.yml file. I think these properties should be added to the default config.yml.. gonna save lot of times to first time installers. It appears it is needed a lot (all the time?) because JIRA api limitations.

**Comment by dnoach** [comment]
@SteveMcGrath can I restrict the number of subtasks generated for a subtask via the config.yml?
I would prefer to say not have more than 200 subtasks generated for a task ticket.

**Comment by kamalmudgal1** [comment]
Hi @dnoach, 

If you can edit the screen into the Jira Project in which you want to have the tasks open to the "Task Management Edit/View/Create Issue Screen". That will resolve your issue.

**Comment by alpesh-te** [comment]
@dnoach let me know if you are still facing the issue or feel free to close the ticket.
