### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by dnoach** [tenable/integration-jira-cloud#167]
@SteveMcGrath  It will be great if we could configure the script to simply create a count of hosts detected with a vulnerability or better yet a text list of all hosts. 

When there are thousands of hosts detected with a vulnerability creating thousands of subtasks for a vuln task is way too excessive.. frankly unworkable. 

If there is something like that available will be great to know how to configure.

**Comment by SteveMcGrath** [comment]
Honestly for something like that would require a completely different workflow, and would require stripping metadata and caching the information in a separate datastore before handling.

This workflow not only matches the Jira on-prem plugin originally developed, is also designed to require minimal pre-processing of the vulnerability information when creating the tickets.

The intended workflow here was to merry the data between a and b to create tasks around each vulnerability and then have subtasks for each unique finding as different teams could then be assigned the relevant findings to work on.

If the current format is undesirable, you always have the option of contacting Tenable pro-serve to customize to fit your needs, or even make the modifications yourself (it is an open source integration after all).

**Comment by dnoach** [comment]
ty @SteveMcGrath yeah agreed. I am looking into customizing it myself.
