### ISSUE TITLE
getting some weird errors when running tenable-jira config.yaml

### ISSUE THREAD

**Issue by nilldot** [tenable/integration-jira-cloud#17]
I'm running the  tenable-jira config.yaml on CentOS 7 VM with Python 3.6 installed via scl and environment changes by "scl enable rh-python36 bash" , but get the below. Config file looks OK

[root@localhost ~]# tenable-jira config.yaml --setup-only
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/tenable-jira", line 11, in <module>
    load_entry_point('tenable-jira-cloud==1.1.3', 'console_scripts', 'tenable-jira')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tenable_jira/cli.py", line 57, in cli
    logging.basicConfig(**log)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1829, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): service

Any advise anyone ?
Thanks!

**Comment by SteveMcGrath** [comment]
can you paste in your config?

**Comment by nilldot** [comment]
it's basic config based on https://github.com/tenable/integration-jira-cloud/blob/master/example_config_file.yaml sir.

###config file
tenable:
  # Tenable.io or API Access Key
  access_key: REPLACED

  # Tenable.io or API Secret Key
  secret_key: REPLACED

jira:
  # The API Token to use to authenticate to the Jira application
  api_token: REPLACED

  # The User that will be authenticaing to the Jira application
  api_username: REPLACED

  # The address pointing to the Jira application.
  address: REPLACED.atlassian.net

project:
  # The lead account id for the primary user for the project.
  leadAccountId: REPLACED-927a-2f2fcf64217d

# The following log definitions are optional.  Only specify these if you want
# to change the default logging behavior of only outputting warnings and errors
# to the screen.
log:
  # What is the logging level desired?  Available levels are:
  #   debug, info, warn, error
  # The default level if unspecified is "warn"
  level: warn

  # If you would like the log output to goto a file instead of standard output,
  # then specify the filename here:
  filename: /var/log/tenable_logfile.log

  # The following section is optional.  You should only specify this section if
  # you would like the bridge to run as a service with it's own timer.
  service:
    # How many hours should we wait between jobs?  Note setting this to a
    # non-zero number will result in imports past the initial import will use
    # time of the last completed import as the basis for last observed.
    interval: 24


Thank you

**Comment by r1ckyb0nd** [comment]
you should not need config.yaml if you are using --setup-only
try just tenable-jira --setup-only

**Comment by SteveMcGrath** [comment]
@nilldot the issue is that the service declaration is on the wrong indentation.  it should be

```yaml
service:
  interval: 24
```

and not:

```yaml
  service:
    interval: 24
```

Basically its just indented a level too much.  YAML can be fickle here.

@r1ckyb0nd  you'll still need a minimal config to inform the integration how to initially connect and build everything out.  it will generate a new config that you can use going forward from that point.  There are some minor limitations to running the setup-only mode, mainly that if the code is updated to use a new field, you'd need to re-run the config generator.

**Comment by nilldot** [comment]
Thanks guys, it works now!
