### ISSUE TITLE
Automatically Setting Due Dates

### ISSUE THREAD

**Issue by Amish-H4ck3r** [tenable/integration-jira-cloud#170]
Love the project, thank you for creating it!!

Apologies in advance if this feature exists and I simply missed it, but I did poke around first before asking.

Is it possible to automatically set the "Due Date" field in Jira based on the "Severity" and "Vulnerability First Seen" fields?

For example, using the SLA schedule below for vulnerability remediation, could the script look at the "Severity" field and add 15 days to the "Vulnerability First Seen" field to automatically set the "Due Date" field for a critical vuln?

Critical: 15 Days
High: 30 Days
Medium: 60 Days
Low: 90 Days

**Comment by Amish-H4ck3r** [comment]
Pretty please?  With sugar on top?

**Comment by kmplngj** [comment]
I think this could easily be done with the Jira Automations.
