### ISSUE TITLE
Only 1 subtask created for vulnerability (task)

### ISSUE THREAD

**Issue by rbernsteinIIC** [tenable/integration-jira-cloud#174]
There are several vulnerabilities that affect several systems.  Rather than creating a subtask for each system a new task and subtask are created.  From other documentation for the on-prem version and a demo we were shown multiple subtasks should be created.  All of our tasks (vulnerabilities) only have one subtask. I found this note in config.py. Is this now the intended functionality?

"This section defines the issue-types & how to search them. There should only ever be a singular "standard" and no more than 1 "subtask". The issue-type name is what will be used throughout the rest of the config file to determine what issue-type gets what data fields."

**Comment by n-mcintosh** [comment]
I am seeing this behavior as well and would like clarification that this is expected behavior.

**Comment by SteveMcGrath** [comment]
can you please post a debug

**Comment by alpesh-te** [comment]
@n-mcintosh seems working for you. Feel free to close the issue
