### ISSUE TITLE
Having issue running tenable-jira --options

### ISSUE THREAD

**Issue by bizznasty** [tenable/integration-jira-cloud#176]
Hello,

I am able to do the basic run by just "tenable-jira config.yaml"

However I am trying to run it with the options available -s and -f. However whenever I try to run
tenable-jira -f -s $(date -v-1d +%s) config.yaml

I get an error:

tenable-jira -f -s $(date -v-1d +%s) tenable_jira.yaml
Get-Date : A parameter cannot be found that matches parameter name 'v-1d'.
At line:1 char:27
+ tenable-jira -f -s $(date -v-1d +%s) tenable_jira.yaml
+                           ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Date], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetDateCommand
 
Usage: tenable-jira [OPTIONS] [CONFIGFILE]
Try 'tenable-jira --help' for help.

Error: Invalid value for '--observed-since' / '-s': 'tenable_jira.yaml' is not a valid integer.

Please advise.

Thank you

**Comment by SteveMcGrath** [comment]
the "$(date -v-1d +%s)" part of the command is unix-specific.

**Comment by nixdat** [comment]
> the "$(date -v-1d +%s)" part of the command is unix-specific.

Hi SteveMcGrath, 
I'm also experiencing the same issue, based on your answer running this integration with the -s option in windows won't work. As I don't have any other option but to run this integration on a windows server. By any chance is there a way to run the -s option on a windows server? I need the job to run every 24 hours and only import the newest vulnerabilities.   
Is this possible? 
Thanks, Nick

**Comment by spatelte** [comment]
@nixdat, you can use Get-date for powershell and 'date' for linux following command for previous date.
- Windows (get-date (get-date).addDays(-1) -UFormat %s)
- Linux date -d "-1 day" +%S

Thanks,

**Comment by nixdat** [comment]
> @nixdat, you can use Get-date for powershell and 'date' for linux following command for previous date.
> 
> * Windows (get-date (get-date).addDays(-1) -UFormat %s)
> * Linux date -d "-1 day" +%S
> 
> Thanks,

Thank you @spatelte I didn't think to do this but will give it a go 

Thanks, Nick

**Comment by alpesh-te** [comment]
@nixdat Let me know if you have any further questions. Feel free to close ticket.
