### ISSUE TITLE
Duplicate vulnerabilities are created for the same vulnerability and same IP

### ISSUE THREAD

**Issue by kmplngj** [tenable/integration-jira-cloud#186]
When the integration is restarted it creates all Jira subtask again. Anything I could do to fix this?

![Screenshot 2022-06-10 at 09 11 51](https://user-images.githubusercontent.com/562965/173010628-820871be-bac7-4c5f-8171-4d97fb2b248d.png)

`issue_types:
- name: Task
  search:
  - Tenable Plugin ID
  type: standard
- name: Sub-task
  platform:
    tenable.io: &id001
    - Tenable Platform
    - Tenable Plugin ID
    - Tenable Asset UUID
    - Vulnerability Port
    - Vulnerability Protocol
    tenable.sc:
    - Tenable Platform
    - Tenable Plugin ID
    - Tenable Asset UUID
    - Device IPv4 Addresses
    - Device IPv6 Addresses
    - Vulnerability Port
    - Vulnerability Protocol
  search: *id001
  type: subtask`

**Comment by kmplngj** [comment]
![Screenshot 2022-06-27 at 08 31 18](https://user-images.githubusercontent.com/562965/175874203-3f84b288-9fc5-4faf-8f0f-c2bec2b0fbc7.png)

It also duplicates the main tasks.

Any idea what could be wrong here? @SteveMcGrath

Thanks
Jan

**Comment by SteveMcGrath** [comment]
what version is this on?

**Comment by kmplngj** [comment]
1.2.3

**Comment by SteveMcGrath** [comment]
can you post the config?

**Comment by kmplngj** [comment]
[issue_debug.md](https://github.com/tenable/integration-jira-cloud/files/9062417/issue_debug.md)

**Comment by kmplngj** [comment]
@SteveMcGrath Any idea?
