### ISSUE TITLE
New findings not being updated

### ISSUE THREAD

**Issue by luisbrandao-zh** [tenable/integration-jira-cloud#189]
We had the integration running for some time managed by someone that has left the team. We currently have the project created and some old findings and I was trying to set it up again.

I set the debug mode and I can see the script lists the findings on tenable.io but I never see the new findings being imported on Jira, after that it just enters a sleep state. All that without a single error. 

I may have missed something...

**Comment by luisbrandao-zh** [comment]
Here is the config file

```tenable:
  # Tenable.io or API Access Key
  access_key: *******

  # Tenable.io or API Secret Key
  secret_key: *******

jira:
  # The API Token to use to authenticate to the Jira application
  api_token: ******

  # The User that will be authenticaing to the Jira application
  api_username: *******

  # The address pointing to the Jira application.
  address: ****.atlassian.net

project:
  # The lead account id for the primary user for the project.
  leadAccountId: ******

# The following log definitions are optional.  Only specify these if you want
# to change the default logging behavior of only outputting warnings and errors
# to the screen.
log:
  # What is the logging level desired?  Available levels are:
  #   debug, info, warn, error
  # The default level if unspecified is "warn"
  level: debug 

  # If you would like the log output to goto a file instead of standard output,
  # then specify the filename here:
  filename: *****/logfile.log

# The following section is optional.  You should only specify this section if
# you would like the bridge to run as a service with it's own timer.
service:
  # How many hours should we wait between jobs?  Note setting this to a
  # non-zero number will result in imports past the initial import will use
  # time of the last completed import as the basis for last observed.
  interval: 24```

**Comment by SteveMcGrath** [comment]
if its been a long while since its last been run, you may want to run it with the since flag set to the last run time to catch up.  also you may want to set the age parameter in the tenable section to the number of days between runs.

**Comment by GlenAshwood** [comment]
This is now working. 

Even though I was an administrator, I needed to add scan and view permissions

**Comment by alpesh-te** [comment]
@luisbrandao-zh seems permission issue. The [Tenable.io](http://tenable.io/) user not only has to be a Admin but also has to have explicit ‘can view’ access permissions to the  ‘all assets’ to export vulns from all assets via the /vulns/export API endpoint. Feel free to close it.
