### ISSUE TITLE
Split Description, Solution and Output

### ISSUE THREAD

**Issue by dil-FBond** [tenable/integration-jira-cloud#19]
Can the three parts of the description field be broken out. This will greatly enhance our searching ability as a lot of the times the description field as keys words that we either do or don't want in our solution searches. 

Example would be to search for all solution that have don't have patch in them. Currently this can only be done by searching the JIRA description as a whole and would give a wrong result.

**Comment by SteveMcGrath** [comment]
These were originally kept together as if split up, they wouldn't be visible in the description field.  As for the specific example you have, it might make sense to expose the has_patch flag as a custom field.

**Comment by dil-ddsouza** [comment]
It looks like the attribute 'has_patch' is of tenable IO. Do you know what is the equivalent for tenable SC please? 
https://developer.tenable.com/docs/tenable-plugin-attributes

**Comment by SteveMcGrath** [comment]
if patchPubDate has anything, then it has a patch:

https://github.com/tenable/pyTenable/blob/master/tests/sc/test_analysis.py#L593

**Comment by SteveMcGrath** [comment]
As this isn't an issue with the code, can be resolved with a config change, and that adding fields is more customization of the existing config rather than anything else.  I'll be closing this.
