### ISSUE TITLE
Missing "Tenable Asset Tags" when creating issue in Jira

### ISSUE THREAD

**Issue by phumatakeda1998** [tenable/integration-jira-cloud#196]
We are integrating Tenable.sc with Jira. We met a problem when creating issue that though all fields in Asset tab of sub task such as Tenable Asset UUID, Tenable Platform, Device Hostname... displays, Field name **Tenable Asset Tags** did not display though we have set tag for Host asset in Tenable.sc. 

How can we sovle this problem?

I'll really hope your reply soon
Thanks

**Comment by SteveMcGrath** [comment]
Tenable.sc as Asset Groups, not Tags.
