### ISSUE TITLE
Import Lower severity Vulns

### ISSUE THREAD

**Issue by kwentenable** [tenable/integration-jira-cloud#20]
Default the integration only imports critical and high severity vulnerabilities. 

If I wanted to import lows and mediums would I modify the config.py and add - medium and low to this section?:

 # Tenable.io vulnerability severities to convert to JIRA tickets.
  tio_severities:
    - high
    - critical

**Comment by SteveMcGrath** [comment]
https://github.com/tenable/integration-jira-cloud/issues/18#issuecomment-595455330
