### ISSUE TITLE
Missing direct link to vulnerability

### ISSUE THREAD

**Issue by Datosecurity** [tenable/integration-jira-cloud#203]
How do we add a tenable link to the actual vulnerability in Jira for the individual vulnerabilities?    If the user needs more info they can click the link and login to Tenable to see the exact ticket.   Is this even possible. 

Thanks,

EL

**Comment by SteveMcGrath** [comment]
As there is no stable, documented way to construct the URL programmatically at this point, it's not something that's doable.  That's not saying that down the road their may not be a better approach, just none that won't likely change in 6-12mo.
