### ISSUE TITLE
Asset information missing

### ISSUE THREAD

**Issue by Datosecurity** [tenable/integration-jira-cloud#204]
How do we include more information from the assets from Tenable? 
Example: 
 DNS (FQDN)  =  Full name that is different than simple DNS
System type= example: azure-instance

Cloud resource information: 
Azure Location
Azure Resource group or ID

Cloud Tags like Team and Owner  (each asset has a tag) 

This information is readily available in Tenable. Anyway to map it in Jira-tenable project?   It will help assign and find machines faster to multiple teams and owners.

**Comment by Datosecurity** [comment]
The config.py file does include mappings like this one below.  But the aseset.fqdn isnt really showing the real fqdn that is useful. 
 
 jira_field: Device DNS Name
    type: readonlyfield
    searcher: textsearcher
    issue_type:
      - Sub-task
    tio_field: asset.fqdn
    tsc_field: dnsName

**Comment by SteveMcGrath** [comment]
asset.fqdn is a singular FQDN that's pulled down from the vulnerability API.  If you would like to have the FQDN list from the asset export API, then you would need to get those fields added in first.  They aren't pulled down by default as the Asset metadata then has to be stored in memory for all asset data and then stitched back together on the fly.


An example showcasing how that can be done is here:

https://github.com/tenable/integration-jira-cloud/issues/81#issuecomment-724799379

**Comment by alpesh-te** [comment]
@Datosecurity Do yo need any further information? Feel free to close the ticket.
