### ISSUE TITLE
Tenable.io and Jira Cloud integration

### ISSUE THREAD

**Issue by div-4-git** [tenable/integration-jira-cloud#208]
We are trying to follow the steps for setting up the [tenable.io](http://tenable.io/) and JIRA cloud integration as given here - https://github.com/tenable/integration-jira-cloud

But we also found in an article within JIRA that the integration works only manually. Is there a way to automate this? Pls refer to comments by Kalpana Gautam (dated - 22/Jun/2021 9:46 AM) in this article - https://jira.atlassian.com/browse/API-104

**Comment by spatelte** [comment]
@div-4-git Tenable-jira integration is standalone tool, it's run after interval which is set in custom config file.

you can check https://github.com/tenable/integration-jira-cloud/blob/master/example_config_file.yaml

**Comment by samryanturner** [comment]
I've stuck it in CI for better scheduling and duration monitoring.
