### ISSUE TITLE
Distribute tickets

### ISSUE THREAD

**Issue by lisaegor1** [tenable/integration-jira-cloud#209]
Hi!
Is it posssible to distribute tickets between teams depending on the resource tag or nessus scaner that we used 
For example:
Report from scanner#1 --> assign tickets to team#1 (or person#1)
Report from scanner#2 --> assign tickets to team#2 (or person#2)

**Comment by alpesh-te** [comment]
Hi @lisaegor1 with current implementation we don't have a provision to assign multiple users.

**Comment by kmplngj** [comment]
@lisaegor1 We do this with [Jira Automations](https://www.atlassian.com/software/jira/features/automation).
