### ISSUE TITLE
Unable to leverage User Filtering on custom fields

### ISSUE THREAD

**Issue by obrientg** [tenable/integration-jira-cloud#21]
Hello Stephen! 

In getting some of the data form Tenable into Jira, I'm working on building some dashboards in Jira. Unfortunately it seems that some of the key custom fields that would be useful in dashboards are configured in such a way that Jira is unable to use them. Seems just a text field does not work, they would need to be a 'Group picker', 'Multi select', 'User picker', 'Select list' and 'Version picker' fields.

Some research pointed me to similar issues/questions of this nature: 
https://community.atlassian.com/t5/Jira-questions/Jira-Custom-Field-Missing-Issues-in-Filter-result/qaq-p/806568
https://community.atlassian.com/t5/Jira-Service-Desk-questions/User-Filtering-on-custom-fields-missing/qaq-p/949718
https://community.atlassian.com/t5/Jira-questions/Jira-Two-Dimensionnal-Filter-Custom-field-missing/qaq-p/405284

If the fields have to be a specific list (a finite list, rather than an open text field), then the fields that would fall into this bucket would be: 

- Tenable Plugin ID
- Tenable Plugin Family
- Tenable Plugin Name
- Vulnerability Severity
- Vulnerability State
- Vulnerability Port
- Vulnerability Protocol

Any chance of getting these fields updated in this project, so that we can create additional & more meaningful charts/dashboards for those that live and breathe Jira/Confluence?

Thanks!

**Comment by SteveMcGrath** [comment]
Many of these fields this isn't possible. 


* **Plugin ID**: There are over 100 thousand plugin IDs and this number grows every day.
* **Tenable Plugin Family**: While this number is much more static, new families do get added over time, therefore there isn't a static, distinct set.
* **Tenable Plugin Name**: Every plugin has a unique name.  See plugin id.
* **Vulnerability Severity**: This could be technically possible, however would require breaking changes from the existing integration.
* **Vulnerability State**: As the state of the vulnerability is effectively managed by the state of the ticket (open == active, closed == remediated), not sure of the additional value here.
* **Vulnerability Port**: 65,536 potential numbers.
* **Vulnerability Protocol**: This could be technically possible, however would require breaking changes from the existing integration.

**Comment by dil-FBond** [comment]
can you give an example of a dashboard you are looking to create. I have not had any issue searching on any of the above types?
