### ISSUE TITLE
Removed Assets / Not Closing

### ISSUE THREAD

**Issue by ghost** [tenable/integration-jira-cloud#217]
We have the asset age functionality enabled to remove any assets not seen for 14 days. I've noticed that the integration is not closing these down inside our Jira instance. I understand it is the last thing the job will do when executing and nothing seems to happen.

**Comment by samryanturner** [comment]
I'll look to get some logs but essentially it gets to the last stage, then exits 0.

**Comment by samryanturner** [comment]
`19:56:06 2023-02-03 19:56:06,189 tenable_jira.transform.Tio2Jira INFO Discovered terminated or deleted assets. Attempting to clean up orphaned issues.
19:56:06 2023-02-03 19:56:06,189 tenable_jira.jira.Jira DEBUG Request: {"method": "POST", "url": "https://sg-infotech.atlassian.net/rest/api/3/search", "params": {}, "body": {"jql": "project = \"VULN\" AND \"Tenable Asset UUID\" in (\"de8228c2-321b-4048-b9e0-effff7de8094\") AND status not in (Closed, Done, Resolved)"}}
19:56:06 2023-02-03 19:56:06,346 urllib3.connectionpool DEBUG [https://sg-infotech.atlassian.net:443](https://sg-infotech.atlassian.net/) "POST /rest/api/3/search HTTP/1.1" 200 None
19:56:06 [Office365connector] Matched status 'SUCCESS' for webhook with name 'Jira - Tenable Import'.
19:56:06 Finished: SUCCESS`

**Comment by samryanturner** [comment]
Is there any additional information needed?

Seem to have a large variance between To Do in Jira and numbers in Tenable.io.

**Comment by spatelte** [comment]
@samryanturner I have checked long you have submitted, but I'm not able to conclude from this. If you can share more logs or log file that will  be good.

you can share log file spate.ctr at tenable.com

**Comment by samryanturner** [comment]
@spatelte sure thing, gathering logs now using --troubleshoot and will share.

**Comment by samryanturner** [comment]
Just on how we're setup,

We have it running twice a day, once at midnight, then again at 1PM. It runs simply with the paramter of the config file but should we be adding a "since when" parameter aswell? Not sure best practice on running.
