### ISSUE TITLE
Ignore/Exclude specific findings / plugins

### ISSUE THREAD

**Issue by PwnDexter** [tenable/integration-jira-cloud#221]
Hey, is there a way in the config.yaml to specific certain plugins/findings you want ignored and not sent to Jira? I have exclusion lists setup in Tenable but still getting the issues being created in Jira. Thanks!

**Comment by spatelte** [comment]
@PwnDexter Current Jira cloud do not have any filtration for plugins/findings, but you can use tio_severities to 
please check: https://github.com/tenable/integration-jira-cloud/blob/master/tenable_jira/config.py#L45
