### ISSUE TITLE
Tenable Asset Tags not showing in Jira Subtasks

### ISSUE THREAD

**Issue by cornesto** [tenable/integration-jira-cloud#223]
We configured a connecter in AWS running on Ubuntu 22. We successfully setup the script to run as a service and has been working well. However, the asset Tags we've set in Tenable.io are not being transferred over to Jira tickets. I looked through the transform.py script in `/usr/local/lib/python3.10/dist-packages/tenable_jira/transform.py` and did notice the following:
```
                # iterate over the tags
                for tag in asset['tags']:
                    # Generate the tag name to use.
                    tag_name = '{key}:{value}'.format(
                        key=tag['key'].replace(' ', '_'),  # << references 'key' field
                        value=tag['value'].replace(' ', '_') # << references 'value' field
```
 The snippet above is iterating over the "tags" attribute and looking for the 'key' and 'value' field for the respective tag. However, when I tested a manual GET for asset details, the "tags" attribute uses 'tag_key' and 'tag_value' fields, not 'key' and 'value'. (https://developer.tenable.com/reference/assets-asset-info)

Any suggestions or something else I've missed to get the tags to work?

**Comment by spatelte** [comment]
@cornesto  For the above code snip we are replacing space with underscore, which is not cause for fetching assets with tags. If you can share config and logs that will help.
