### ISSUE TITLE
Modify workflow

### ISSUE THREAD

**Issue by armada-lmt** [tenable/integration-jira-cloud#239]
Will anything with the script break if I modify the workflow in the Jira project to include a PENDING state between TODO and DONE?  Often we have vulnerabilties that should get fixed in our next OS update cycle so we like to mark them PENDING so we don't need to keep discussing them.

**Comment by SteveMcGrath** [comment]
vulnerabilities are considered in an active and maintained state as long as they arent in one of the configured done states.
