### ISSUE TITLE
New (?) Tenable and Jira Cloud Integration Built-in to Tenable.io

### ISSUE THREAD

**Issue by cc-vy** [tenable/integration-jira-cloud#246]
I stumbled onto a built in Jira cloud integration that is present in Tenable.io settings.  

I am interested in switching, but i am concerned about the custom fields that creates interfering with the ones that are in use by the GitHub version of the project.  I do not want to switch until i trust that the built-in version does what i need. 

I would not usually bother except that I am the only one in my organization that understands how the GitHub version works.  Also, presumably Support would step in and help resolve issues if using the built-in version. 

 Has anyone that currently uses the GitHub version tried this built in version out? Perhaps at the same time using 2 different projects that can advise?

**Comment by SteveMcGrath** [comment]
Couple of things @cc-vy:

1.  The Jira connector within the TVM UI would be supported by Tenable support (and not here).  The documentation for it is at: https://docs.tenable.com/integrations/Atlassian/jira-cloud/Content/introduction.htm
2. As I recently got this Jira integration back from the previous team, I have been working on a rewrite of the integration to resolve some of the long-standing issues with the current implementation.  Current progress is in the other branch that has been receiving updates.  I'd expect the v2 to be released within the coming weeks.

Ultimately the decision is yours as to which path you choose to take, just trying to give you the options available.

**Comment by SteveMcGrath** [comment]
For reference, just released the rewrite.  Please take a look and see if the improvements are worth switching to the newer codebase.
