### ISSUE TITLE
Filter assets by tag

### ISSUE THREAD

**Issue by havengit** [tenable/integration-jira-cloud#247]
In V1 version,   can filter asset with follow configuration.
In V2 version , how to filter asset with tenable tag  ?

tio_tags:
   - key: 
     value:

**Comment by SteveMcGrath** [comment]
With the newer Access Control system in TVM, there isn't a need anymore to to that in the config.  Simply adjust the ACLs for that user within the TVM Access Control config.  This solution ends up being a lote more flexible than what we had in the v1 config.
