### ISSUE TITLE
Issue with RestApi Response from Jira

### ISSUE THREAD

**Issue by kmplngj** [tenable/integration-jira-cloud#251]
Hi! 

I now get an error message when trying to build the config. I had the old version running for month without issues but in the last weeks also got the same errors there and I don't know why.

I did not change any of the config in Jira, not the project, not the user.

```
AttributeError: Could not determine Issue Type id for Task:standard
```

The Issue Type id for Task:standard used in the project should be 10012.

<img width="755" alt="image" src="https://github.com/tenable/integration-jira-cloud/assets/562965/12df4b15-18fd-47a9-9e7a-09469c5d4f37">

Perhaps you have an idea how to fix this. For me it looks like there is a bug in Jira but I could not imagine how this could be...

Thanks a lot
Jan

**Comment by SteveMcGrath** [comment]
So if you happen to know the ids for the task and subtask, you can add it to the config and then it wont have to try to figure it out.

What you will look for is two parts in the config, `[jira.subtask]` and `[jira.task]`.  On the next line after each, add a new `id` parameter and just specify the issue type id.  So it should look something like:

```toml
[jira.task]
id      = 10012
name    = “Task”
type    = “standard”
```

That should easily bypass that part.
