### ISSUE TITLE
PermissionError: [WinError 32]

### ISSUE THREAD

**Issue by HotSpoon-ColdMango** [tenable/integration-jira-cloud#252]
The sync performs as intended but continue to get the following error:

PermissionError: [WinError 32] The process cannot access the file because it is
being used by another process: 'mapping.db'

**Comment by SteveMcGrath** [comment]
when is the error occuring?  can you provide some more detail or logs?

**Comment by HotSpoon-ColdMango** [comment]
![image](https://github.com/tenable/integration-jira-cloud/assets/96836092/90bba69e-8f9c-4c21-b9a6-3855916cde74)

**Comment by HotSpoon-ColdMango** [comment]
Good looking out. Was hosting the file on a cloud, the amount of time needed to process change syncs to the cloud was keeping it open and causing the error.

**Comment by HotSpoon-ColdMango** [comment]
Is there a way to change the configuration of this to work in conjunction with the "built-in" integrator:
![image](https://github.com/tenable/integration-jira-cloud/assets/96836092/d30775ff-e454-4f90-9ee9-25c17969901d)

Or does it have to be one or the other?

**Comment by SteveMcGrath** [comment]
They do work differently, so it would be either-or.  Basically choose the one that works best for you use case.  The in-product one you dont have to run, however this one does have a lot more customization potential.
