### ISSUE TITLE
Tag contain space 

### ISSUE THREAD

**Issue by havengit** [tenable/integration-jira-cloud#253]
![image](https://github.com/tenable/integration-jira-cloud/assets/20832243/37b0eee6-62ab-4ef5-90c1-c7e0f33e8391)

The space allow used in tenable. but sync failed.

**Comment by havengit** [comment]
https://github.com/tenable/integration-jira-cloud/issues/223
According this issue , Can the community follow this for a quick fix？

**Comment by SteveMcGrath** [comment]
let me release a new rev with the fix.  Apologies for the regression.

**Comment by SteveMcGrath** [comment]
2.0.2 released to pypi with the corrected code.
