### ISSUE TITLE
Tenable account privileges

### ISSUE THREAD

**Issue by havengit** [tenable/integration-jira-cloud#255]
![Uploading image.png…]()

Requirements for tenable account permissions ：
Tenable.io API Keys associated to an account with "CanView" permissions for "AllAssets" (required for the Vuln Export APIs)
Tenable.sc API Keys associated to an account with full access to the vulnerability data.
For Tenable.sc, an Analysis Query ID that represents the query to run against the vulnerability data.

We created an account and authorized only some of his assets. With this account from tenable can see the vulnerability and asset information. jira create project is working. No information is synchronized to jira. the script output is as above.

**Comment by SteveMcGrath** [comment]
Can you give me some more details?  What platform are you communicating with?  That image never uploaded.

**Comment by havengit** [comment]
There some error in sql,Please check follow logs:

OperationalError: (sqlite3.OperationalError) near "ON": syntax error
[SQL: INSERT INTO task (plugin_id, jira_id, updated) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), 
(?, ?, ?), (?, ?, ?) ON CONFLICT DO NOTHING]
[parameters: ('51192', 11089, '2024-05-20 14:33:40.354078', '65821', 11085, '2024-05-20 14:33:40.354078', '104743', 11082, '2024-05-20 14:33:40.354078', 
'157288', 11078, '2024-05-20 14:33:40.354078', '70658', 11077, '2024-05-20 14:33:40.354078', '10114', 11076, '2024-05-20 14:33:40.354078', '57582', 11075, 
'2024-05-20 14:33:40.354078', '187315', 11070, '2024-05-20 14:33:40.354078', '42873', 11069, '2024-05-20 14:33:40.354078', '58453', 11068, '2024-05-20 
14:33:40.354078', '153953', 11067, '2024-05-20 14:33:40.354078')]
(Background on this error at:https://sqlalche.me/e/20/e3q8)

**Comment by havengit** [comment]
I am not a developer and then analyzed the error with ChatGPT. Made the following changes and then could successfully synchronize.
![image](https://github.com/tenable/integration-jira-cloud/assets/20832243/e6c84136-f929-4059-8f8a-0e3410d9dc2a)

https://github.com/tenable/integration-jira-cloud/blob/main/tenb2jira/processor.py
From
.on_conflict_do_nothing()
to
.prefix_with('OR IGNORE')

**Comment by havengit** [comment]
Another issue was find.
All issue's  priority  in jira was  medium .

**Comment by havengit** [comment]
![image](https://github.com/tenable/integration-jira-cloud/assets/20832243/c6507fe6-a744-43f8-9930-7ee9948a9a99)

**Comment by SteveMcGrath** [comment]
Looking into the priority issue right now.

**Comment by SteveMcGrath** [comment]
2.0.3 Is running through the release deployment as we speak.  Please let me know if that fixes the issues.

**Comment by havengit** [comment]
Thanks for fast fix. The code has upgrade to 2.0.3.
issue1, sql error fixed
issue2, The fix not work.  I have a workaround ,Useing the jira automation to map finding serverity to jira prioriy. Also disable the map under jira field  in config
#map_to_priority = true

**Comment by havengit** [comment]
issue3,After tenable add recast vulnerability  severity from medium to high, But not synchronized to jira

**Comment by havengit** [comment]
issue3, when add recast rule to change the severity from critical to medium.  This change will not sync to jira "Finding Severity" or "Vulnerability Severity"

**Comment by SteveMcGrath** [comment]
For these other issues, please file other issues so that they can be tracked independently, thanks.

**Comment by havengit** [comment]
Ok got it ,will rise new issue .
