### ISSUE TITLE
Severity  change will not sync to jira

### ISSUE THREAD

**Issue by havengit** [tenable/integration-jira-cloud#257]
when add recast rule to change the severity from critical to medium. This change will not sync to jira "Finding Severity" or "Vulnerability Severity"

**Comment by SteveMcGrath** [comment]
Alrighty, 2.0.4 is running through release right now.  Please test and let me know if this solves the issue.

**Comment by havengit** [comment]
issue is not fixed

**Comment by SteveMcGrath** [comment]
This should be addressed in 2.0.5.  My own testing seems to confirm this.

**Comment by havengit** [comment]
Hi, I have test it . if remove last_run from config  and use 2.0.5 version .This issue was fixed.  so I need remove  last_run  before every run ?

**Comment by SteveMcGrath** [comment]
no, going forward it'll pull the deltas.  so as the findings get updated from scans, the issues should update.
