### ISSUE TITLE
Sub-task's state is to do, but task is done

### ISSUE THREAD

**Issue by havengit** [tenable/integration-jira-cloud#262]
Sub-task's state is to do, but task is done

**Comment by SteveMcGrath** [comment]
Can run an automation task to re-open those closed tasks && test with 2.0.5?  If you are still seeing issues, I'd like you to set the max_workers to `1` and run again to bypass the thread execution workers.

**Comment by havengit** [comment]
yes, set max_workers to 1 and verison 2.0.5, The issue was fix . And the task in "done" state will be reopen to "to do". I think this issue was fixed
