### ISSUE TITLE
Sync error 

### ISSUE THREAD

**Issue by havengit** [tenable/integration-jira-cloud#265]
Hi developer,  
    I get some error when sync. then sync stopped
{"errorMessages":["The operator \'=\' is not supported by the \'Tenable Asset UUID\' field."],"warningMessages":[]}

**Comment by havengit** [comment]
body = {                                                                              │ │
│ │               │   'jql': 'project = "VULN" AND issuetype = "Sub-task" AND "Tenable Asset     │ │
│ │               UUID" = "787086d4'+243,                                                        │ │
│ │               │   'expand': [],                                                              │ │
│ │               │   'fields': ['id', 'key']                                                    │ │
│ │               }                                                                              │ │
│ │   box_attrs = {}                                                                             │ │
│ │    conv_box = True                                                                           │ │
│ │   conv_json = False                                                                          │ │
│ │         err = <class 'restfly.errors.BadRequestError'>                                       │ │
│ │  error_resp = '[400: POST] https://xxxx.atlassian.net/rest/api/3/search                   │ │
│ │               body=b\'{"errorMessages":["The operator \\\'=\\\' is not supported by the      │ │
│ │               \\\'Tenable Asset UUID\\\' field."],"warningMessages":[]}\''                   │ │
│ │      kwargs = {                                                                              │ │
│ │               │   'json': {                                                                  │ │
│ │               │   │   'jql': 'project = "VULN" AND issuetype = "Sub-task" AND "Tenable Asset │ │
│ │               UUID" = "787086d4'+243,                                                        │ │
│ │               │   │   'expand': [],                                                          │ │
│ │               │   │   'fields': ['id', 'key']                                                │ │
│ │               │   },                                                                         │ │
│ │               │   'verify': True                                                             │ │
│ │               }                                                                              │ │
│ │      method = 'POST'                                                                         │ │
│ │      params = {}                                                                             │ │
│ │        path = 'search'                                                                       │ │
│ │        resp = <Response [400]>                                                               │ │
│ │     retries = 0                                                                              │ │
│ │ retry_codes = []                                                                             │ │
│ │       rkeys = None                                                                           │ │
│ │        rval = 'REDACTED'                                                                     │ │
│ │        self = <tenb2jira.jira.api.session.JiraAPI object at 0x7f2685fd04c0>                  │ │
│ │      status = 400                                                                            │ │
│ │         uri = 'https://xxx.atlassian.net/rest/api/3/search'                              │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │

**Comment by SteveMcGrath** [comment]
Can you confirm that the `Tenable Asset UUID` field is a labels type within Jira?

**Comment by havengit** [comment]
- Because we use tenable to integrate jira's plugin at the same time, it creates some feilds that are the same as this project, causing the synchronization to fail. After deleting it, it works fine. This is not a bug. Please close this issue . 
- I really appreciate your quick response.
- This project is the official open source project of tenable. It seems and tenable.io plugin logic and jira content is not the same. Will this project be maintained all the time. We prefer this project.

**Comment by SteveMcGrath** [comment]
Yes, maintenance will continue with this project.  We just completed a massive rewrite of the project to modernize the code and solve a lot of readability and maintainability issues with the v1 codebase.  If you have any requests or features you would like to see, please feel free to submit an issue and notate it as a feature request.
