### ISSUE TITLE
Jira Issue Tokens are Deleted?

### ISSUE THREAD

**Issue by cc-vy** [tenable/integration-jira-cloud#266]
I have recently seen that my Jira searches are not working properly.  They are failing to find simple things.  I opened a support ticket with Jira, and after quite some time, they came back with this:

_- We have Jira issue tokens, which are generated based on an issue's Summary and description fields when an issue is created and saved in the database against those issues.
- All these Jira issue tokens are like keywords, which JQL later uses to search for and retrieve the respective Jira issues. 
- In our case we have observed that these Jira issue tokens are getting deleted periodically every 24 hours. 
- Because these Jira issue tokens, which are keywords used by JQL to accurately search issues, are deleted, hence our JQL search is not working properly. 
- We have observed that the Vulnerability Last Seen field and the Parent field are updated daily on these impacted issues.
- We have also observed that the Jira issue tokens gets deleted at the same time when these two fields are updated.
- However, we can see from the issue history that the Vulnerability Last Seen and Parent fields are not manually updated; rather, they are periodically updated every 24 hours by some kind of third-party tool or integration. We have confirmed that this field is not updated by any Automation rule._

The 3rd party tool is this one, of course.  

Also, I have noticed that the parent issues keep getting updated to the same thing.  It just started happening at some point. 

 updated the Parent
May 28, 2024 at 10:00 AM
and then it shows the same ticket to the same ticket number. 

I am still using the last version of 1 here and am waiting to update to the new version until some of the issues are resolved and i can determine how to switch properly, without causing a lot of disruption to the production process.   

But I am not really sure why this would delete any kind of jira issue token nor am i sure why the parent keeps getting updated. 

Thoughts on that?  Is there any thought on whether the new version would have the same issue?  I have a lot of filters and rules on the Jira side that do not work properly because of this.

**Comment by SteveMcGrath** [comment]
v1 of the codebase is much slower, but if its working for you, then great.  While we wont be writing any future updates to it, I expect the remaining issues with the current codebase to be quickly resolved.  There is also a config template that will leverage the existing fields from the v1 codebase as a starting point.  Apologize that this couldn't have been easier, however the old code was simply a bear to try to fix, and so many of the issues we were working through were simply config-related issues due to spacing requirements in YAML.

As for the issues at hand, I wonder why updating the issue is deleting those tokens.  The integration has no understanding of anything outside of the fields it's managing.

v1 will always update the parent if a new subtask is created/updated.  This is simply as it was not storing anything and would never assume that the data on the parent task was correct.

v2 will only update the parent when the plugin modification time or vpr update time has been updated.

**Comment by cc-vy** [comment]
Understand why you switched -- just need to figure out how do it with minimal disruption. 

V1 is working fine for now, but it is updating the parent for the subtask on every already existing subtask every single day regardless of any new subtasks or changes to the one it is updating.   It updates the parent to the same parent every run regardless of whether the parent has new subs, or the sub itself has updates for every single subtask that is open. 

So every ticket shows something like this in the history:

JIRA 
 updated the Parent May 29, 2024 at 10:01 AM
VM-21964 -> VM-21964

JIRA 
 updated the Parent May 28, 2024 at 10:01 AM
VM-21964  -> VM-21964

JIRA 
 updated the Parent May 27, 2024 at 10:01 AM
VM-21964 -> VM-21964

As to the token issue, it does seem like something happening with the API function on their side- I did not think you were doing anything explicitly with these tokens (that i was not even aware of) but thought i would ask. 

Thanks

**Comment by SteveMcGrath** [comment]
the v1 codebase will always update the parent and the subtask together, which is likely why you're seeing that.  So if ANY of the subtasks get updated, then the parent gets updated as well for EACH of the subtasks (it's not efficient, I know, but originally the assumption was no db at all).


The token issue is definitely not anything on our end, unless their API docs are incorrect in how the update works.  I would assume that they updates are NOT atomic (everything in the issue gets replaced with whatever we send, incl. the fields we aren't sending), however it may be worth asking them about that, as it may have a larger implication if so.

**Comment by cc-vy** [comment]
Ah i see.  Ok -- i will ask and update as to the response.

**Comment by cc-vy** [comment]
I have just had a response from Jira support saying that they think maybe you fixed the issue with the issues tokens here:
https://github.com/tenable/integration-jira-cloud/pull/260

I understand that you will not be fixing anything related to version 1, but i have my doubts about this being related to the problem they are investigating.  

Does it seem to you that whatever change you made for this new version really would resolve this token deleting issue?

**Comment by SteveMcGrath** [comment]
v1 always used the keys instead of the ids.  v2 started to use the IDs instead (as it seemed to make more sense overall) however we ran into a number of issue updating issues using the IDs.  the v2 codebase switched back to using keys (just like v1).

**Comment by cc-vy** [comment]
They have confirmed this is a bug in API
https://jira.atlassian.com/browse/JRACLOUD-83964

Unfortunately, they have to first implement more logging to understand the cause to then implement a fix. This could affect anyone that uses the project though.   
Thanks for your help,  i am going to close this
