### ISSUE TITLE
Error When Connecting Dev Instance of Jira Which Uses Self Signed Certificate

### ISSUE THREAD

**Issue by Kerb1ah** [tenable/integration-jira-cloud#27]
When I try to connect to our Dev instance of Jira I get the following error:

 `Max retries exceeded with url: /rest/api/3/project/XXX (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1051)')))`

The Dev instance does use a self signed certificate and this will probably not change. Is there a way to skip the certificate check if only for the dev instance?

Thanks

**Comment by SteveMcGrath** [comment]
the dev instance of jira cloud uses a self-signed cert?

**Comment by Kerb1ah** [comment]
That's right. I managed to get around it by modifying sessions.py not to validate the cert while I am using it with the Dev instance of Jira.

Apologies if my first message was unclear.
