### ISSUE TITLE
NotRenderableError: unable to render Integer; a string or other renderable object is required

### ISSUE THREAD

**Issue by zaa0777** [tenable/integration-jira-cloud#271]
Hello.
Trying to integrate tenable.sc with Jira cloud.
When run "build" some fields are adding:
........
           INFO     INFO:Jira:Adding field customfield_10338:"Patch Publication Date" to the screen tab "Vulnerability".                                                                             jira.py:166
           INFO     INFO:Jira:Adding field customfield_10339:"Finding Severity" to the screen tab "Vulnerability".                                                                                   jira.py:166
           INFO     INFO:Jira:Adding field customfield_10340:"Tenable Finding ID" to the screen tab "Vulnerability".                                                                                 jira.py:166

But in the end I get the following error
NotRenderableError: unable to render Integer; a string or other renderable object is required

Also, In config file already tried change Page Size from 1000 to more, but no luck.
![1](https://github.com/tenable/integration-jira-cloud/assets/126323329/5f95cf95-1d4a-4a04-a0ca-acb9996510fa)
<img width="688" alt="2" src="https://github.com/tenable/integration-jira-cloud/assets/126323329/5920a62e-4242-4bd3-b1ca-728bd41d6e78">
<img width="665" alt="3" src="https://github.com/tenable/integration-jira-cloud/assets/126323329/b3225473-20a1-4b83-bca9-11ae8be49ee5">
<img width="700" alt="4" src="https://github.com/tenable/integration-jira-cloud/assets/126323329/70cd113b-4be9-40b8-bacf-3fb378931912">

**Comment by SteveMcGrath** [comment]
That looks like an oversight on our end, I'll get it corrected as soon as i can.
