### ISSUE TITLE
Processing errors when running for the first time. 

### ISSUE THREAD

**Issue by kolitsasg** [tenable/integration-jira-cloud#272]
When I run the sync for the first time tickets are created but towards the end the following sample errors appear:
ERROR    ERROR:Processor:badly formed hexadecimal    processor.py:441
                    UUID string
                    NoneType: None

ERROR    ERROR:Processor:(sqlite3.IntegrityError)    processor.py:441
                    UNIQUE constraint failed: task.plugin_id
                    [SQL: INSERT INTO task (plugin_id, jira_id,
                    updated) VALUES (?, ?, ?)]
                    [parameters: ('142960', 'VULN-1140',
                    '2024-06-12 07:32:21.102048')]
                    (Background on this error at:
                    https://sqlalche.me/e/20/gkpj)
                    NoneType: None

After running the sync multiple times the errors stop appearing. I do not see any evident adverse effect at the moment.

**Comment by SteveMcGrath** [comment]
Thats odd, there should never be a nonetype for a plugin ID.  If the issue happens again, please re-open the issue and paste the full traceback from the console.
