### ISSUE TITLE
sync tasks are created for more than 30 days in jira

### ISSUE THREAD

**Issue by Flv-cmd** [tenable/integration-jira-cloud#273]
when I start **sync**  with the script, tasks are created for more than 30 days in jira. Even when I tell him to pull for 1 day, he pulls much more.
I use "**vuln_age        = 30**" parameter and as I see it is useless, the number does not correspond to reality. I tried to create everything again, deleted and rewrote all sorts of parameters what i know. Nothing helps =/

```
# The vulnerability severities to pull.  Supported values are:
# - "critical"
# - "high"
# - "medium"
# - "low"
severities      = ["low", "medium", "high", "critical"]

# How old should we pull back initially to collect the data?  Expecting number
# of calendar days.
vuln_age        = 30
```

and sometimes less.. if after sync  30 I specify for example 100, it does not sync anymore, even after clearing the cache.
It's make me crazy, I'm missing something...

**Comment by SteveMcGrath** [comment]
The age parameter is used as as a fallback for when the last_run parameter is not set.  The last_run parameter is automatically set fromt he integegration at the end of every run and informs the **next** run where to start from.

**Comment by Flv-cmd** [comment]
> The age parameter is used as as a fallback for when the last_run parameter is not set. The last_run parameter is automatically set fromt he integegration at the end of every run and informs the **next** run where to start from.

What I am trying to do is retrieving vulnerabilities only seen for last 30 days, no more than 30 days. How can I do that?

**Comment by Flv-cmd** [comment]
> It should automatically re-pull those findings the next time they are observed. You dont want to pull 30 days every single time if you dont have to. For example:
> 
> 1. Initial Integration run (pulls 30 days back) <-- sets the `last_run` time to "1"
> 2. Integration sync (no new data) <-- Uses `last_run` of "1", then sets it to "2"
> 3. New TVM/TSC Scan completes <-- This data is "newer" than the last run
> 4. Integration sync (Pulls data from new scan) <-- Uses `last_run` of "2", then sets it to "4".

okay, I need to understand this parameter better. He still draws a random amount, despite your instructions. Thanks for the answer

**Comment by SteveMcGrath** [comment]
I know that recently some findings were replayed into the some TVM containers, as the since parameter uses the "indexed_at" time (and not the last_found paramater) this may likely be the cause.  In either case, the integration isnt the one at fault, its the upstream API returning the additional data.
