### ISSUE TITLE
error_code:10; Resource is not supported

### ISSUE THREAD

**Issue by zaa0777** [tenable/integration-jira-cloud#276]
When run "Sync" get next error:
APIError: [403: GET] https://tenable.lan/rest/query/None?fields=filters 
body=b'{"type":"regular","response":"","error_code":10,"error_msg":"Resource is not supported.","warnings":[],"timestamp":1718896970}\n'

<img width="1009" alt="1" src="https://github.com/tenable/integration-jira-cloud/assets/126323329/5c2d9a3e-32fb-403d-bd22-68db1bbb0793">
<img width="500" alt="2" src="https://github.com/tenable/integration-jira-cloud/assets/126323329/fd51add8-2891-4205-b9be-79ea44815c57">
<img width="507" alt="3" src="https://github.com/tenable/integration-jira-cloud/assets/126323329/dabdafdf-f9e6-46c8-963d-35a02019a0ef">
<img width="496" alt="4" src="https://github.com/tenable/integration-jira-cloud/assets/126323329/9ead5ceb-ab84-4467-973c-712760faf3bf">
<img width="505" alt="5" src="https://github.com/tenable/integration-jira-cloud/assets/126323329/ead7320a-bbf9-4cc6-ab00-53ad94ae2d48">

**Comment by SteveMcGrath** [comment]
Well thats not desirable.  The current workaround is to specify a query_id from TSC.

**Comment by zaa0777** [comment]
> Well thats not desirable. The current workaround is to specify a query_id from TSC.

What type of queries must be? Type and Tool?
Im already tried Type - Vulnerability; Tool - Vuln. List; Details List; Summary with different filters
but nothing happend in end, not a single ticket was created in the Jira.

Get only this message:
![зображення](https://github.com/tenable/integration-jira-cloud/assets/126323329/01443264-c052-455b-9677-411b8bbbc8a5)

**Comment by zaa0777** [comment]
After deleting from the configuration file strings with "patch publication dates" managed to create some an issues, but errors were thrown up, and information about the host and IP addresses was not added

I also noticed that vulnerabilities(plugin id) are duplicated and sub-tasks are not created, perhaps due to the fact that information about the hosts themselves is not filled in.

<img width="809" alt="зображення" src="https://github.com/tenable/integration-jira-cloud/assets/126323329/f2bb6179-b244-4890-a172-449723a0e92b">

**Comment by SteveMcGrath** [comment]
Can you email me the full log?

Smcgrath -at- tenable.com

**Comment by zaa0777** [comment]
done

**Comment by zaa0777** [comment]
> Can you email me the full log?
> 
> Smcgrath -at- tenable.com

done

**Comment by SteveMcGrath** [comment]
alrighty, in the interest of figuring out what else is going on here, can I ask you to install the version from the git head and set the `max_workers` config to `1`?

The UUID error is being masked by the multi-threading and I need the traceback to see whats failing there.

```
pip install https://github.com/tenable/integration-jira-cloud/archive/main.zip
```

**Comment by SteveMcGrath** [comment]
Confirmed that the issues have been resolved.
