### ISSUE TITLE
Task closed mistakenly due to no open subtasks

### ISSUE THREAD

**Issue by ltakashvili** [tenable/integration-jira-cloud#277]
Hello

I run sync and I noticed several Tasks were closed due to no open subtasks. But, subtasks are still open. Task shouldn't be closed
![1](https://github.com/tenable/integration-jira-cloud/assets/123452019/636b05dd-6ebe-45ce-bd05-dbf95373720b)
![2](https://github.com/tenable/integration-jira-cloud/assets/123452019/9cf2a7d4-4c80-4c42-b765-8944fbc626f9)

also those vulnerabilities are still open in tenable.

What am I doing wrong?

**Comment by ltakashvili** [comment]
> Can you re-open those tasks that were incorrectly closed and rerun the integration in debug logging? I'd need to see the whole log. Feel free to email it to smcgrath -at- tenable.com

Done, email sent

**Comment by ltakashvili** [comment]
P.S email I sent contained following 2 lines. These were added by me mistakenly. was trying to locate issue in processor.py
![image](https://github.com/tenable/integration-jira-cloud/assets/123452019/347f55ae-fef0-4e86-a48f-94db6b21e701)

**Comment by SteveMcGrath** [comment]
I'm wondering if the initial cache building isn't pulling these subtasks for some reason...

Think you can run with  the following flags?

```
tenb2jira --no-update --no-cleanup --ignore-last-run --verbose
```

then send back the log & the mapping database (as it wont be removed with no-cleanup).

**Comment by SteveMcGrath** [comment]
Also, before you do that, make sure to re-open those findings that were incorrectly closed.

**Comment by ltakashvili** [comment]
> I'm wondering if the initial cache building isn't pulling these subtasks for some reason...
> 
> Think you can run with the following flags?
> 
> ```
> tenb2jira --no-update --no-cleanup --ignore-last-run --verbose
> ```
> 
> then send back the log & the mapping database (as it wont be removed with no-cleanup).

Hello. Apologies for late response
I run command you mentioned above and attached requested files(log and mapping.db)

I already mentioned in the email, but when I run this command, everything went smooth.
Then I run **tenb2jira sync config.toml** which didn't have any issue
then run same command: **tenb2jira sync config.toml** and this second execution had problems (closes tasks)

**Comment by ltakashvili** [comment]
Hello. any updates?

**Comment by SteveMcGrath** [comment]
So if it's working with those flags and not working without, can you run with just 1 flag? `--ignore-last-run`?  If that works as expected, then I think I know what may be happening and how to correct it.  Also, it would mean you have a workaround for now.  It'll take longer to run (as you aren't using deltas) however correctness is more important than speed.

**Comment by ltakashvili** [comment]
> t

Hi

yes it worked very well. speed issue isn't big deal, it's ok for me. thanks a lot

But what was the issue? just wondering. I think it is related to time issue right?

**Comment by SteveMcGrath** [comment]
I think i nailed down the bug for this one.  if you're willing, could you pull from the github branch (and not the version) to test?

```
pip install https://github.com/tenable/integration-jira-cloud/archive/main.zip
```

**Comment by SteveMcGrath** [comment]
@ltakashvili or @kmplngj could confirm that this addresses the issue, I'm not seeing it anymore on my end.

**Comment by ltakashvili** [comment]
> @ltakashvili or @kmplngj could confirm that this addresses the issue, I'm not seeing it anymore on my end.

Hi Steve, tested recently and yes, it seems it's resolved now. thanks a lot
