### ISSUE TITLE
Error when sync: Key "info" does not exist

### ISSUE THREAD

**Issue by ltakashvili** [tenable/integration-jira-cloud#278]
Hello

I had severities variable in config.toml

`severities = ['high', 'critical']`

changed to

`severities      = ["critical", "high", "medium", "low"]`

and when running sync, error shows up

![keyerror](https://github.com/tenable/integration-jira-cloud/assets/123452019/e8b306e8-34cf-485b-acfd-f72a2b1e06f1)

I don't want informational tickets :)

**Comment by SteveMcGrath** [comment]
By chance have you recasted info plugins as non-info?

**Comment by SteveMcGrath** [comment]
#280 https://github.com/tenable/integration-jira-cloud/issues/280#issuecomment-2217750347
