### ISSUE TITLE
Upload only VPR vulnerabilities

### ISSUE THREAD

**Issue by ltakashvili** [tenable/integration-jira-cloud#286]
Hello. 3 questions

1. I would like to upload only those vulnerabilities which have VPR score assigned. Not interested with vulns without any VPR scores. I couldn't find such setting in config file. Previous integration was giving such setting it was parameter: vpr_score or smth like that.

2. Previous jira integration script (before completely rewritten) already created VULN project in my jira. Now, I want to use this new integration and keep old project. can I just use old project (created by previous integration) safely? Reason is that I don't want to give site-admin privileges again to the whole jira. I already have Vulnerability Management project created, on which I have admin privileges.

3. Also, I don't need every custom field such as Finding_ID, how can I prevent such custom fields? I dont want to use some of them

**Comment by SteveMcGrath** [comment]
1. That can certainly be added
2. If you use the migration config file as a basis, you should be able to use the old project without issue.
3. The Finding ID is actually the one required field for the v2 integration, as it's used to identify a unique finding for cache building.  Without that field, we have to serially work over the Jira data one-by-one, which is much slower.

**Comment by ltakashvili** [comment]
> 1. That can certainly be added
> 2. If you use the migration config file as a basis, you should be able to use the old project without issue.
> 3. The Finding ID is actually the one required field for the v2 integration, as it's used to identify a unique finding for cache building.  Without that field, we have to serially work over the Jira data one-by-one, which is much slower.

Thanks.

I used migration config file and everything went smooth on the first try, but on the second sync try I received lots of errors:

`body=b'{"errorMessages":[],"errors":{"summary":"Field \'summary\' cannot be set. It is not on the
                    appropriate screen, or unknown.","customfield_14392":"Field \'customfield_14392\' cannot be set. It is not on the
                    appropriate screen, or unknown.","customfield_14395":"Field \'customfield_14395\' cannot be set. It is not on the
                    appropriate screen, or unknown.","customfield_14396":"Field \'customfield_14396\' cannot be set. It is not on the
                    appropriate screen, or unknown.","customfield_14393":"Field \'customfield_14393\' cannot be set. It is not on the
                    appropriate screen, or unknown.","customfield_14394":"Field \'customfield_14394\' cannot be set. It is not on the
                    appropriate screen, or unknown.","customfield_14399":"Field \'customfield_14399\' cannot be set. It is not on the
                    appropriate screen, or unknown.","description":"Field \'description\' cannot be set. It is not on the appropriate
                    screen, or unknown.","customfield_14400":"Field \'customfield_14400\' cannot be set. It is not on the appropriate
                    screen, or unknown.","customfield_14397":"Field \'customfield_14397\' cannot be set. It is not on the appropriate
                    screen, or unknown.","customfield_14420":"Field \'customfield_14420\' cannot be set. It is not on the appropriate
                    screen, or unknown.","customfield_14398":"Field \'customfield_14398\' cannot be set. It is not on the appropriate
                    screen, or unknown.","priority":"Field \'priority\' cannot be set. It is not on the appropriate screen, or
                    unknown.","customfield_14414":"Field \'customfield_14414\' cannot be set. It is not on the appropriate screen, or
                    unknown.","customfield_14415":"Field \'customfield_14415\' cannot be set. It is not on the appropriate screen, or
                    unknown.","customfield_14401":"Field \'customfield_14401\' cannot be set. It is not on the appropriate screen, or
                    unknown.","customfield_14412":"Field \'customfield_14412\' cannot be set. It is not on the appropriate screen, or
                    unknown.","customfield_14413":"Field \'customfield_14413\' cannot be set. It is not on the appropriate screen, or
                    unknown.","customfield_14402":"Field \'customfield_14402\' cannot be set. It is not on the appropriate screen, or
                    unknown.","customfield_14416":"Field \'customfield_14416\' cannot be set. It is not on the appropriate screen, or
                    unknown.","customfield_14417":"Field \'customfield_14417\' cannot be set. It is not on the appropriate screen, or
                    unknown."}}'`

**Comment by SteveMcGrath** [comment]
Can you run the build command and report back the output?  You should be seeing something like this:

```
❯ tenb2jira build base_config.toml
Configuration loaded: OK
               Tenable Parameters                                              Jira Parameters
┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Parameter         ┃ Value                     ┃ ┃ Parameter         ┃ Value                                             ┃
┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Platform          │ tvm                       │ │ Application URL   │ https://tenable-dev.atlassian.net                 │
│ Severities        │ medium,high,critical      │ │ Username          │ smcgrath@tenable.com                              │
│ Vulnerability Age │ 30                        │ │ API Token         │ ATAT...                                           │
│ Last Run          │ 1720519509                │ │ Closed Transition │ Done                                              │
│ Access key        │ 4da9...6dbe               │ │ Severity Map      │ {'critical': 1, 'high': 2, 'medium': 3, 'low': 4} │
│ Secret key        │ 5699...7a64               │ │ State Map         │ {'open': True, 'reopened': True, 'fixed': False}  │
│ TVM URL           │ https://cloud.tenable.com │ │ Max Workers       │ 5                                                 │
│ Export Chunk Size │ 1000                      │ │ Project Key       │ VTST2                                             │
└───────────────────┴───────────────────────────┘ │ Task Name         │ Task                                              │
                                                  │ Task ID           │ 10101                                             │
                                                  │ Sub-Task Name     │ Sub-task                                          │
                                                  │ Sub-Task ID       │ 10102                                             │
                                                  └───────────────────┴───────────────────────────────────────────────────┘
                                      Jira Fields
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Field Name                    ┃ Jira Id           ┃ Tenable Mapping                  ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Tenable Asset UUID            │ customfield_10285 │ asset.uuid                       │
│ Tenable Asset Tags            │ customfield_10286 │ asset.tags                       │
│ Tenable Platform              │ customfield_10274 │ Tenable Vulnerability Management │
│ Device Hostname               │ customfield_10290 │ asset.hostname                   │
│ Device NetBIOS Name           │ customfield_10291 │                                  │
│ Device DNS Name               │ customfield_10292 │ asset.fqdn                       │
│ Device IPv4 Addresses         │ customfield_10288 │ asset.ipv4                       │
│ Device IPv6 Addresses         │ customfield_10289 │ asset.ipv6                       │
│ Device Network ID             │ customfield_10293 │ asset.network_id                 │
│ Vulnerability Repository ID   │ customfield_10300 │                                  │
│ Vulnerability Repository Name │ customfield_10301 │                                  │
│ CVEs                          │ customfield_10275 │ pluvin.cve                       │
│ Tenable VPR Score             │ customfield_10302 │ plugin.vpr.score                 │
│ CVSSv2 Base Score             │ customfield_10276 │ plugin.cvss_base_score           │
│ CVSSv2 Temporal Score         │ customfield_10277 │ plugin.cvss_temporal_score       │
│ CVSSv3 Base Score             │ customfield_10278 │ plugin.cvss3_base_score          │
│ CVSSv3 Temporal Score         │ customfield_10279 │ plugin.cvss3_temporal_score      │
│ Tenable Plugin ID             │ customfield_10281 │ plugin.id                        │
│ Tenable Plugin Family         │ customfield_10282 │ plugin.family                    │
│ Tenable Plugin Name           │ customfield_10283 │ plugin.name                      │
│ Vulnerability Severity        │ customfield_10284 │ plugin.risk_factor               │
│ Vulnerability First Seen      │ customfield_10294 │ first_found                      │
│ Vulnerability Last Seen       │ customfield_10295 │ last_found                       │
│ Vulnerability Last Fixed      │ customfield_10296 │ last_fixed                       │
│ Vulnerability State           │ customfield_10297 │ state                            │
│ Vulnerability Port            │ customfield_10298 │ port.port                        │
│ Vulnerability Protocol        │ customfield_10299 │ port.protocol                    │
│ Patch Publication Date        │ customfield_10280 │ plugin.patch_publication_date    │
│ Finding Severity              │ customfield_10306 │ severity                         │
│ Tenable Finding ID            │ customfield_10318 │ integration_finding_id           │
└───────────────────────────────┴───────────────────┴──────────────────────────────────┘
```

**Comment by ltakashvili** [comment]
> Can you run the build command and report back the output? You should be seeing something like this:
> 
> ```
> ❯ tenb2jira build base_config.toml
> Configuration loaded: OK
>                Tenable Parameters                                              Jira Parameters
> ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
> ┃ Parameter         ┃ Value                     ┃ ┃ Parameter         ┃ Value                                             ┃
> ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
> │ Platform          │ tvm                       │ │ Application URL   │ https://tenable-dev.atlassian.net                 │
> │ Severities        │ medium,high,critical      │ │ Username          │ smcgrath@tenable.com                              │
> │ Vulnerability Age │ 30                        │ │ API Token         │ ATAT...                                           │
> │ Last Run          │ 1720519509                │ │ Closed Transition │ Done                                              │
> │ Access key        │ 4da9...6dbe               │ │ Severity Map      │ {'critical': 1, 'high': 2, 'medium': 3, 'low': 4} │
> │ Secret key        │ 5699...7a64               │ │ State Map         │ {'open': True, 'reopened': True, 'fixed': False}  │
> │ TVM URL           │ https://cloud.tenable.com │ │ Max Workers       │ 5                                                 │
> │ Export Chunk Size │ 1000                      │ │ Project Key       │ VTST2                                             │
> └───────────────────┴───────────────────────────┘ │ Task Name         │ Task                                              │
>                                                   │ Task ID           │ 10101                                             │
>                                                   │ Sub-Task Name     │ Sub-task                                          │
>                                                   │ Sub-Task ID       │ 10102                                             │
>                                                   └───────────────────┴───────────────────────────────────────────────────┘
>                                       Jira Fields
> ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
> ┃ Field Name                    ┃ Jira Id           ┃ Tenable Mapping                  ┃
> ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
> │ Tenable Asset UUID            │ customfield_10285 │ asset.uuid                       │
> │ Tenable Asset Tags            │ customfield_10286 │ asset.tags                       │
> │ Tenable Platform              │ customfield_10274 │ Tenable Vulnerability Management │
> │ Device Hostname               │ customfield_10290 │ asset.hostname                   │
> │ Device NetBIOS Name           │ customfield_10291 │                                  │
> │ Device DNS Name               │ customfield_10292 │ asset.fqdn                       │
> │ Device IPv4 Addresses         │ customfield_10288 │ asset.ipv4                       │
> │ Device IPv6 Addresses         │ customfield_10289 │ asset.ipv6                       │
> │ Device Network ID             │ customfield_10293 │ asset.network_id                 │
> │ Vulnerability Repository ID   │ customfield_10300 │                                  │
> │ Vulnerability Repository Name │ customfield_10301 │                                  │
> │ CVEs                          │ customfield_10275 │ pluvin.cve                       │
> │ Tenable VPR Score             │ customfield_10302 │ plugin.vpr.score                 │
> │ CVSSv2 Base Score             │ customfield_10276 │ plugin.cvss_base_score           │
> │ CVSSv2 Temporal Score         │ customfield_10277 │ plugin.cvss_temporal_score       │
> │ CVSSv3 Base Score             │ customfield_10278 │ plugin.cvss3_base_score          │
> │ CVSSv3 Temporal Score         │ customfield_10279 │ plugin.cvss3_temporal_score      │
> │ Tenable Plugin ID             │ customfield_10281 │ plugin.id                        │
> │ Tenable Plugin Family         │ customfield_10282 │ plugin.family                    │
> │ Tenable Plugin Name           │ customfield_10283 │ plugin.name                      │
> │ Vulnerability Severity        │ customfield_10284 │ plugin.risk_factor               │
> │ Vulnerability First Seen      │ customfield_10294 │ first_found                      │
> │ Vulnerability Last Seen       │ customfield_10295 │ last_found                       │
> │ Vulnerability Last Fixed      │ customfield_10296 │ last_fixed                       │
> │ Vulnerability State           │ customfield_10297 │ state                            │
> │ Vulnerability Port            │ customfield_10298 │ port.port                        │
> │ Vulnerability Protocol        │ customfield_10299 │ port.protocol                    │
> │ Patch Publication Date        │ customfield_10280 │ plugin.patch_publication_date    │
> │ Finding Severity              │ customfield_10306 │ severity                         │
> │ Tenable Finding ID            │ customfield_10318 │ integration_finding_id           │
> └───────────────────────────────┴───────────────────┴──────────────────────────────────┘
> ```

Currently I don't have site-admin privileges and I think I can't run this command (as I understand it creates new project and new fields which requires site-admin).

is there other ways to troubleshoot this problem?

**Comment by ltakashvili** [comment]
> it'll simply run the checks to see what has been created based off the config and will only attempt to build anything that appears to be missing.

> ltakashvili@tenable-integration:~/new_env$ tenb2jira build config.toml
Configuration loaded: OK
               Tenable Parameters                                              Jira Parameters
┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Parameter         ┃ Value                     ┃ ┃ Parameter         ┃ Value                                             ┃
┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Platform          │ tvm                       │ │ Application URL   │ https://adjara.atlassian.net                      │
│ Severities        │ low,medium,high,critical  │ │ Username          │ jira_vulnerability@adjarabet.com                  │
│ Vulnerability Age │ 90                        │ │ API Token         │ ATAT...                                           │
│ Last Run          │ None                      │ │ Closed Transition │ Done                                              │
│ Access key        │ 8867...48f8               │ │ Severity Map      │ {'critical': 1, 'high': 2, 'medium': 3, 'low': 4} │
│ Secret key        │ 433c...3552               │ │ State Map         │ {'open': True, 'reopened': True, 'fixed': False}  │
│ TVM URL           │ https://cloud.tenable.com │ │ Max Workers       │ 4                                                 │
│ Export Chunk Size │ 1000                      │ │ Project Key       │ VULN                                              │
└───────────────────┴───────────────────────────┘ │ Task Name         │ Task                                              │
                                                  │ Task ID           │ 10001                                             │
                                                  │ Sub-Task Name     │ Sub-task                                          │
                                                  │ Sub-Task ID       │ 10002                                             │
                                                  └───────────────────┴───────────────────────────────────────────────────┘
                                      Jira Fields
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Field Name                    ┃ Jira Id           ┃ Tenable Mapping                  ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Tenable Asset UUID            │ customfield_14403 │ asset.uuid                       │
│ Tenable Asset Tags            │ customfield_14404 │ asset.tags                       │
│ Tenable Platform              │ customfield_14391 │ Tenable Vulnerability Management │
│ Device Hostname               │ customfield_14408 │ asset.hostname                   │
│ Device NetBIOS Name           │ customfield_14409 │                                  │
│ Device DNS Name               │ customfield_14410 │ asset.fqdn                       │
│ Device IPv4 Addresses         │ customfield_14406 │ asset.ipv4                       │
│ Device IPv6 Addresses         │ customfield_14407 │ asset.ipv6                       │
│ Device Network ID             │ customfield_14411 │ asset.network_id                 │
│ Vulnerability Repository ID   │ customfield_14418 │                                  │
│ Vulnerability Repository Name │ customfield_14419 │                                  │
│ CVEs                          │ customfield_14392 │ pluvin.cve                       │
│ Tenable VPR Score             │ customfield_14420 │ plugin.vpr.score                 │
│ CVSSv2 Base Score             │ customfield_14393 │ plugin.cvss_base_score           │
│ CVSSv2 Temporal Score         │ customfield_14394 │ plugin.cvss_temporal_score       │
│ CVSSv3 Base Score             │ customfield_14395 │ plugin.cvss3_base_score          │
│ CVSSv3 Temporal Score         │ customfield_14396 │ plugin.cvss3_temporal_score      │
│ Tenable Plugin ID             │ customfield_14398 │ plugin.id                        │
│ Tenable Plugin Family         │ customfield_14399 │ plugin.family                    │
│ Tenable Plugin Name           │ customfield_14400 │ plugin.name                      │
│ Vulnerability Severity        │ customfield_14401 │ plugin.risk_factor               │
│ Vulnerability First Seen      │ customfield_14412 │ first_found                      │
│ Vulnerability Last Seen       │ customfield_14413 │ last_found                       │
│ Vulnerability Last Fixed      │ customfield_14414 │ last_fixed                       │
│ Vulnerability State           │ customfield_14415 │ state                            │
│ Vulnerability Port            │ customfield_14416 │ port.port                        │
│ Vulnerability Protocol        │ customfield_14417 │ port.protocol                    │
│ Patch Publication Date        │ customfield_14397 │ plugin.patch_publication_date    │
│ Finding Severity              │ customfield_14402 │ severity                         │
│ Tenable Finding ID            │ customfield_14605 │ integration_finding_id           │
└───────────────────────────────┴───────────────────┴──────────────────────────────────┘
ltakashvili@tenable-integration:~/new_env$

**Comment by SteveMcGrath** [comment]
hmm, that all looks alright.  can you run it again with the verbose settings?  What I'd like you to look for is to check to ensure that the screens it's selecting are the correct ones.  You should only see **2** IDs, and those should correlate to the **Create** and the **Edit/View** Screen.  If these are **NOT** matching, that would be the root cause.  I should be able to correct this by allowing you to manually override the screen selection, however need to know whats happening here first.

![CleanShot 2024-08-12 at 10 34 52](https://github.com/user-attachments/assets/260b564c-b82b-415a-bc13-5635712606ce)

![CleanShot 2024-08-12 at 10 46 52](https://github.com/user-attachments/assets/d60f4f97-7044-454e-ab69-62275d6f0309)

![CleanShot 2024-08-12 at 10 47 18](https://github.com/user-attachments/assets/be91a143-2f3c-432f-bdf3-3a338e51adc1)

**Comment by SteveMcGrath** [comment]
Added initial support for vpr threshholding with the newly optional `vpr_score` parameter within the tenable section of the config.  please take a look and let me know if that solves the VPR problem.

**Comment by ltakashvili** [comment]
> hmm, that all looks alright. can you run it again with the verbose settings? What I'd like you to look for is to check to ensure that the screens it's selecting are the correct ones. You should only see **2** IDs, and those should correlate to the **Create** and the **Edit/View** Screen. If these are **NOT** matching, that would be the root cause. I should be able to correct this by allowing you to manually override the screen selection, however need to know whats happening here first.
> 
> ![CleanShot 2024-08-12 at 10 34 52](https://private-user-images.githubusercontent.com/254700/357113651-260b564c-b82b-415a-bc13-5635712606ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTM0MDksIm5iZiI6MTcyNDA1MzEwOSwicGF0aCI6Ii8yNTQ3MDAvMzU3MTEzNjUxLTI2MGI1NjRjLWI4MmItNDE1YS1iYzEzLTU2MzU3MTI2MDZjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwNzM4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGVmZTFhNDdmMDUxMzcxMGI1N2IwM2UxMGZkZGNhZjQ5NGMzZmY1ZmIyYWYwZWNiOWU4ZmI3ZTE3MGNiNTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T0WGhdj0xIEnkAfTDZ3cOF0Qs3gmXc7VZKP6PmBCXXo)
> 
> ![CleanShot 2024-08-12 at 10 46 52](https://private-user-images.githubusercontent.com/254700/357114575-d60f4f97-7044-454e-ab69-62275d6f0309.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTM0MDksIm5iZiI6MTcyNDA1MzEwOSwicGF0aCI6Ii8yNTQ3MDAvMzU3MTE0NTc1LWQ2MGY0Zjk3LTcwNDQtNDU0ZS1hYjY5LTYyMjc1ZDZmMDMwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwNzM4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTFjMzFkODcyZWM3YTJlZDQwNTdmNmEwOWUzMzA3OTNmZWFmN2Q2NzQyYzdiZWUzZWY3MzhmZjgxZmZhZTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jImqWe-uym6PrgTntXFR0gcBETssyAjcgcqjYGYiv0E)
> 
> ![CleanShot 2024-08-12 at 10 47 18](https://private-user-images.githubusercontent.com/254700/357114998-be91a143-2f3c-432f-bdf3-3a338e51adc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTM0MDksIm5iZiI6MTcyNDA1MzEwOSwicGF0aCI6Ii8yNTQ3MDAvMzU3MTE0OTk4LWJlOTFhMTQzLTJmM2MtNDMyZi1iZGYzLTNhMzM4ZTUxYWRjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwNzM4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDQ3MzlkNWVlNjdkMzFlYjM4YzZhODRhOWU3ZTUwM2E0ODFiNzAzZTlkNThiNjg5MjE1YmI4MTJkYWFiZmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zsZ9kxVIC_x90DzmJ5fpSErgH2vQRQbLAhT3fa3nKao)

it seems screen IDs match
![image](https://github.com/user-attachments/assets/a87685f2-2f09-47af-b4b3-64658eda1d34)
![image](https://github.com/user-attachments/assets/165dff0e-6840-4e54-ae31-cddaf7dde3a0)
![image](https://github.com/user-attachments/assets/429098de-7240-4285-b078-626f83431be5)

but what I noticed is new activity
![image](https://github.com/user-attachments/assets/8ff06338-6440-462c-99c3-b9689513cdd6)
![image](https://github.com/user-attachments/assets/9d9186cf-d7ba-4296-aae4-95312b4e34c7)

**Comment by SteveMcGrath** [comment]
This is really bizarre...

Firstly, can I have you set the max_workers to "1" in the config and run again?  I'd ideally like to get the full traceback if you can get it.  Feel free to email it to smcgrath _at_ tenable.com.

**Comment by ltakashvili** [comment]
> This is really bizarre...
> 
> Firstly, can I have you set the max_workers to "1" in the config and run again? I'd ideally like to get the full traceback if you can get it. Feel free to email it to smcgrath _at_ tenable.com.

done

**Comment by SteveMcGrath** [comment]
Looking at the data now.  Can you confirm that the issue type IDs for task and subtask?  From your output it looks like the following:

```
Task Name         │ Task     
Task ID           │ 10001    
Sub-Task Name     │ Sub-task 
Sub-Task ID       │ 10002    
```

If the actual task and subtask assigned to the project isn't those, we can correct it.

**Comment by ltakashvili** [comment]
> Looking at the data now. Can you confirm that the issue type IDs for task and subtask? From your output it looks like the following:
> 
> ```
> Task Name         │ Task     
> Task ID           │ 10001    
> Sub-Task Name     │ Sub-task 
> Sub-Task ID       │ 10002    
> ```
> 
> If the actual task and subtask assigned to the project isn't those, we can correct it.

![image](https://github.com/user-attachments/assets/82757152-b39c-4a20-abc0-7e1aa12a83bd)
![image](https://github.com/user-attachments/assets/0ebd89ab-5ed2-4785-9cc9-b6cd9be7b776)

**Comment by SteveMcGrath** [comment]
so to correct those, just put the correct ids in the task and subtask sections.
