### ISSUE TITLE
 ERROR    ERROR:Processor:could not convert string to float: ''   processor.py:457

### ISSUE THREAD

**Issue by zerokid** [tenable/integration-jira-cloud#291]
had issue during sync

[06:53:17] INFO     INFO:Processor:Matched Task "ADETSC-1" to SQL Cache and updated.                                                            processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-2" to SQL Cache and updated.                                                            processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-4" to SQL Cache and updated.                                                            processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-3" to SQL Cache and updated.                                                            processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-7" to SQL Cache and updated.                                                            processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-8" to SQL Cache and updated.                                                            processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-5" to SQL Cache and updated.                                                            processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-6" to SQL Cache and updated.                                                            processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-9" to SQL Cache and updated.                                                            processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-11" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-10" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-12" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-13" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-14" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-15" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-16" to SQL Cache and updated.                                                           processor.py:194
[06:53:18] INFO     INFO:Processor:Matched Task "ADETSC-17" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-20" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-18" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-19" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-21" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-1" to SQL Cache and updated.                                                            processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-22" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-23" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-24" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-25" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-26" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-28" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-27" to SQL Cache and updated.                                                           processor.py:194
[06:53:19] INFO     INFO:Processor:Matched Task "ADETSC-35" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-31" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-32" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-30" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-35" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-30" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-32" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-33" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-2" to SQL Cache and updated.                                                            processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-3" to SQL Cache and updated.                                                            processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-34" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-34" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-33" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-37" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-36" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-37" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-38" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-39" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-37" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-38" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-39" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-37" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-38" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-1" to SQL Cache and updated.                                                            processor.py:194
[06:53:20] INFO     INFO:Processor:Matched Task "ADETSC-39" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-36" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-38" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-39" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-37" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-38" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-39" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-43" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-42" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Finding related to Plugin 156860 is closed, skipping                                                         processor.py:174
           INFO     INFO:Processor:Finding related to Plugin 202043 is closed, skipping                                                         processor.py:174
           INFO     INFO:Processor:Matched Task "ADETSC-44" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-43" to SQL Cache and updated.                                                           processor.py:194
           INFO     INFO:Processor:Matched Task "ADETSC-42" to SQL Cache and updated.                                                           processor.py:194
           ERROR    ERROR:Processor:list index out of range                                                                                     processor.py:457
                    NoneType: None                                                                                                                              
                    Stack (most recent call last):                                                                                                              
                      File "/Library/Frameworks/Python.framework/Versions/3.12/bin/tenb2jira", line 8, in <module>                                              
                        sys.exit(app())                                                                                                                         
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/typer/main.py", line 309, in                        
                    __call__                                                                                                                                    
                        return get_command(self)(*args, **kwargs)                                                                                               
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1157, in                       
                    __call__                                                                                                                                    
                        return self.main(*args, **kwargs)                                                                                                       
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/typer/core.py", line 723, in main                   
                        return _main(                                                                                                                           
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/typer/core.py", line 193, in _main                  
                        rv = self.invoke(ctx)                                                                                                                   
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1688, in                       
                    invoke                                                                                                                                      
                        return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                 
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1434, in                       
                    invoke                                                                                                                                      
                        return ctx.invoke(self.callback, **ctx.params)                                                                                          
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke                 
                        return __callback(*args, **kwargs)                                                                                                      
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/typer/main.py", line 692, in                        
                    wrapper                                                                                                                                     
                        return callback(**use_params)                                                                                                           
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tenb2jira/cli.py", line 144, in                     
                    sync                                                                                                                                        
                        processor.sync(cleanup=cleanup)                                                                                                         
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tenb2jira/processor.py", line 457,                  
                    in sync                                                                                                                                     
                        log.exception(job.exception(), stack_info=True)                                                                                         
           ERROR    ERROR:Processor:could not convert string to float: ''                                                                       processor.py:457
                    NoneType: None                                                                                                                              
                    Stack (most recent call last):                                                                                                              
                      File "/Library/Frameworks/Python.framework/Versions/3.12/bin/tenb2jira", line 8, in <module>                                              
                        sys.exit(app())                                                                                                                         
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/typer/main.py", line 309, in                        
                    __call__                                                                                                                                    
                        return get_command(self)(*args, **kwargs)                                                                                               
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1157, in                       
                    __call__                                                                                                                                    
                        return self.main(*args, **kwargs)                                                                                                       
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/typer/core.py", line 723, in main                   
                        return _main(                                                                                                                           
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/typer/core.py", line 193, in _main                  
                        rv = self.invoke(ctx)                                                                                                                   
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1688, in                       
                    invoke                                                                                                                                      
                        return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                 
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1434, in                       
                    invoke                                                                                                                                      
                        return ctx.invoke(self.callback, **ctx.params)                                                                                          
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke                 
                        return __callback(*args, **kwargs)                                                                                                      
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/typer/main.py", line 692, in                        
                    wrapper                                                                                                                                     
                        return callback(**use_params)                                                                                                           
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tenb2jira/cli.py", line 144, in                     
                    sync                                                                                                                                        
                        processor.sync(cleanup=cleanup)                                                                                                         
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tenb2jira/processor.py", line 457,                  
                    in sync                                                                                                                                     
                        log.exception(job.exception(), stack_info=True)                                                                        
......

 ERROR    ERROR:Processor:list index out of range                                                                                     processor.py:457
                    NoneType: None                                                                                                                              
                    Stack (most recent call last):                                                                                                              
                      File "/Library/Frameworks/Python.framework/Versions/3.12/bin/tenb2jira", line 8, in <module>                                              
                        sys.exit(app())                                                                                                                         
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/typer/main.py", line 309, in                        
                    __call__                                                                                                                 

......

          ERROR    ERROR:Processor:could not convert string to float: ''                                                                       processor.py:457
                    NoneType: None                                                                                                                              
                    Stack (most recent call last):                                                                                                              
                      File "/Library/Frameworks/Python.framework/Versions/3.12/bin/tenb2jira", line 8, in <module>                                              
                        sys.exit(app())                                                                                                                         
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/typer/main.py", line 309, in                        
                    __call__                                                                                                                                    
                        return get_command(self)(*args, **kwargs)                                                                                               
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1157, in                       
                    __call__                                                                                                                                    
                        return self.main(*args, **kwargs)                                                                                                       
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/typer/core.py", line 723, in main                   
                        return _main(                                                                                                                           
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/typer/core.py", line 193, in _main                  
                        rv = self.invoke(ctx)                                                                                                                   
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1688, in                       
                    invoke                                                                                                                                      
                        return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                 
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1434, in                       
                    invoke                                                                                                                                      
                        return ctx.invoke(self.callback, **ctx.params)                                                                                          
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke                 
                        return __callback(*args, **kwargs)                                                                                                      
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/typer/main.py", line 692, in                        
                    wrapper                                                                                                                                     
                        return callback(**use_params)                                                                                                           
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tenb2jira/cli.py", line 144, in                     
                    sync                                                                                                                                        
                        processor.sync(cleanup=cleanup)                                                                                                         
                      File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tenb2jira/processor.py", line 457,                  
                    in sync                                                                                                                                     
                        log.exception(job.exception(), stack_info=True)                                                                                         
           ERROR    ERROR:Processor:Refusing to continue (1547 errors) & terminating sync.                                                      processor.py:463

**Comment by zerokid** [comment]
i change to worker 1 and check what is the cause

<img width="842" alt="Screenshot 2024-08-13 at 9 36 46 AM" src="https://github.com/user-attachments/assets/4e659b52-6948-4bee-9dc5-3542e625d208">

**Comment by zerokid** [comment]
i update field.py to this

` if isinstance(value, list):
            if len(value) > 1:
                operator = 'in'
                vals = [f'"{str(i)}"' for i in value]
                value = f'({",".join(vals)})'
            elif len(value) == 1:
                value = f'"{str(value[0])}"'
            else:  # If the list is empty
                operator = 'is'
                value = 'EMPTY'`

**Comment by SteveMcGrath** [comment]
I've corrected the issue in multiple places, and also added some additional testing to confirm that the issue should be resolved.
