### ISSUE TITLE
Incorrect time format within Security Center integrations.  Possibly timzone/timing issue?

### ISSUE THREAD

**Issue by zerokid** [tenable/integration-jira-cloud#292]
After make the second snyc call this error will return 

<img width="1280" alt="Screenshot 2024-08-13 at 12 57 38 PM" src="https://github.com/user-attachments/assets/8a43e158-0dbb-4e1e-8f26-9cd58ce4153f">

**Comment by SteveMcGrath** [comment]
alrighty, should be corrected now.

**Comment by zerokid** [comment]
its still not working

**Comment by SteveMcGrath** [comment]
Thats really odd, as I can't seem to replicate that.  From the debug logs on 2.0.9 it appears that everything is working as expected.  Timezones shouldn't matter for unix timestamps, as they count seconds since 1/1/1970 UTC.  The only thing i could think of is maybe the time is wrong on the SC host itself?

Note that in the filter I'm seeing the STARTTIME-ENDTIME format expected:

```json
{"filterName": "lastSeen", "operator": "=", "value": "1723552747-1723742640"}
```

Log even (formatted for readability) from a TSC sync with `--verbose`:

```
DEBUG    DEBUG:tenable.sc.TenableSC:Request: {
    "method": "POST",
    "url": "https://sc.tenalab.online/rest/analysis",
    "params": {},
    "body": {
        "type": "vuln",
        "sourceType": "cumulative",
        "query": {
            "tool": "vulndetails",
            "type": "vuln",
            "filters": [
                {"filterName": "ip", "operator": "=", "value": "10.238.64.0-10.238.64.255"},
                {"filterName": "severity", "operator": "=", "value": "2,3,4"},
                {"filterName": "lastSeen", "operator": "=", "value": "1723552747-1723742640"}
            ],
            "startOffset": 0,
            "endOffset": 1000
        }
    }
}
```

**Comment by zerokid** [comment]
This is what i notice in my config it will add the last run timestamp
<img width="733" alt="Screenshot 2024-08-16 at 7 02 26 AM" src="https://github.com/user-attachments/assets/31e03b52-f55b-4d07-a692-f1801753e200">

as i check it actually get the wrong unix timestamp. im on gmt+8 and it suppose to reflect +8 7AM 
<img width="713" alt="Screenshot 2024-08-16 at 7 06 01 AM" src="https://github.com/user-attachments/assets/29b0d618-9bc4-4aaf-b234-f502404dcf35">


this is my verbose output
<img width="964" alt="Screenshot 2024-08-16 at 7 04 07 AM" src="https://github.com/user-attachments/assets/16004c5f-72b2-41c1-8189-77858daebc7b">

**Comment by SteveMcGrath** [comment]
I'm quite confused.  Looking at this:

The timestamp of the last run is set here: https://github.com/tenable/integration-jira-cloud/blob/main/tenb2jira/tenable/tenable.py#L29
The timestamp of the current run is set here: https://github.com/tenable/integration-jira-cloud/blob/main/tenb2jira/tenable/tenable.py#L89
And the timestamp filter is built here: https://github.com/tenable/integration-jira-cloud/blob/main/tenb2jira/tenable/tenable.py#L102

All of these times are on the same host, so even if timezones were an issue, they should be uniformly an issue.  How you are getting `1723791640` (16-8-2024 07:00:40) to `1723762981` (8-15-2024 23:03:01) in GMT on both is odd.  I'll look into this further Monday morning.

**Comment by SteveMcGrath** [comment]
so i did find something that _may_ have caused this.  spent a bit of time cleaning up all the timestamps to always use UTC regardless.

**Comment by SteveMcGrath** [comment]
Give that commit a try:

```
pip install https://github.com/tenable/integration-jira-cloud/archive/refs/heads/fix/timestamps.zip
```

**Comment by SteveMcGrath** [comment]
2.0.10 entered release with the changes
