### ISSUE TITLE
Number values quoted on Jira Request

### ISSUE THREAD

**Issue by crosenberger-neogov** [tenable/integration-jira-cloud#294]
After the upgrade to 2.0.9, Jira sync is failing on the CVSS score update claiming the numbers are over the max.  It looks like the JSON was updated to quote the number value on those values causing the update to fail as Jira is expecting the number value unquoted. 

in version 2.0.8 

`"customfield_18621": 3.6, "customfield_18622": 2.6, "customfield_18623": 1.9, "customfield_18624": 3.7, "customfield_18625": 0.0,`

in version 2.0.9

`"customfield_18621": "6.7", "customfield_18622": "10.0", "customfield_18623": "7.4", "customfield_18624": "8.8", "customfield_18625": "7.7",`

**Comment by SteveMcGrath** [comment]
That....makes sense.  I was noticing some odd behavior on my test instances where the fields weren't updating UNLESS i did that.  I'll revert the change and release a 2.0.10 this afternoon.

**Comment by SteveMcGrath** [comment]
2.0.10 entering release cycle
