### ISSUE TITLE
Bug when run build parameter

### ISSUE THREAD

**Issue by grn9951** [tenable/integration-jira-cloud#296]
When i run the command tenb2jira build script.toml i always getting the error AttributeError: Could not determine Issue type id for task:standard. All the permissions with users are ok but the script always return this message.

**Comment by SteveMcGrath** [comment]
can you find the issuetype IDs for Task and SubTask?  Can you paste in the debug logs?

**Comment by grn9951** [comment]
I'll get this info. Where the debug logs of tenb2jira are stored?

**Comment by SteveMcGrath** [comment]
run the integration again with the `--debug` flag and either tee the output to a file or copy/paste it.

**Comment by grn9951** [comment]
The flag debug isn't available for me: 
![image](https://github.com/user-attachments/assets/9ba4a1e1-90ac-4c81-ab03-1961968769ef)

**Comment by SteveMcGrath** [comment]
if you are on the latest version, you can run `tenb2jira sync --debug <CONFIG_FILE>`

**Comment by grn9951** [comment]
Hi Steve, i updated the version on environment, from 2.09 to 2.10, the error still the same but this time was possible run the debug option. The file is attached with the output of command, i hide all api and secret keys, atlassian addresses and lead account ids, but in our file we have the correct information. 
[debug_22-08_att.txt](https://github.com/user-attachments/files/16710728/debug_22-08_att.txt)

**Comment by grn9951** [comment]
Hi @SteveMcGrath do you have any updates about this problem? 
Tkss

**Comment by SteveMcGrath** [comment]
So it appears that you have renamed the task and subtask issuetypes to something other than whats expected.  Also that neither issuetype is a subtask of the other.

```
│ │               'https://internalhost.atlassian.net/rest/api/3/issuetype/13737', 'id': '13737',    │ │
│ │               'description': 'Tenable Managed Vulnerability Issue Type', 'iconUrl':          │ │
│ │               'https://internalhost.atlassian.net/rest/api/2/universal_avatar/view/type/issuety… │ │
│ │               'name': 'Tenable Vulnerability', 'subtask': False, 'avatarId': 11500,          │ │
│ │               'hierarchyLevel': 0}, {'self':                                                 │ │
│ │               'https://internalhost.atlassian.net/rest/api/3/issuetype/13738', 'id': '13738',    │ │
│ │               'description': 'Tenable Managed Vulnerability Host Issue Type', 'iconUrl':     │ │
│ │               'https://internalhost.atlassian.net/rest/api/2/universal_avatar/view/type/issuety… │ │
│ │               'name': 'Tenable Vulnerability Host', 'subtask': False, 'avatarId': 11500,     │ │
│ │               'hierarchyLevel': 0}]
```

You could attempt to link them by adding the ID field to the relevent task and subtask definitions within the config file, however this is currently untested with issuetypes that arent parent-child related.

This would likely require a larger update to support this.

**Comment by grn9951** [comment]
Hi Steve, i added this values because even when i creating a new project, i received the the error "Could not determine Issue Type id for Task:standard". This behaviour stopped only when i insert the value of respective task and subtask created by tenable on jira integration. There is another form to do this integration? I don't know how i can i do for more troubleshooting about this problem. Tks

**Comment by SteveMcGrath** [comment]
Well there is a couple of things going on here:

1. Both of these issuetypes are of the same tier, so they may not link properly within Jira (the integration assumes a Task -> Subtask relationship).
2. The current codebase has hardcoded the names "Task" and "Subtask" (the defaults from Jira).  So even if you could get past the initial error, without the correct issuetypes, you'll keep running into problems down the road.
3. Without the parent/child relationship of taska and subtasks, the interlinking between them will be broken, this will lead to a lot of orphaned data.

My suggestion would be to delete these issuetypes that you have created.  Then add the issuetype IDs to the config.  You can discover those manually doing the following:

1. Goto the *Project Settings -> Issue types* Screen
2. Click the *Task* issuetype from the screen, then copy the issuetype id and paste it into the task

![CleanShot 2024-09-03 at 11 55 45](https://github.com/user-attachments/assets/4f66c4b6-2288-4cec-ace7-fb66854b85be)

```toml
[jira.task]
id = 10101
```

3. Do the same thing for the subtask
4. Verify that all of the [permissions detailed in the readme](https://github.com/tenable/integration-jira-cloud?tab=readme-ov-file#permissions) are set for the user running the integration

If the task and subtask issuetypes are not named "Task" and Subtask" within the project, it may actually be easier to simply delete the project and have the integration recreate a new one with the appropriate permissions.

**Comment by SteveMcGrath** [comment]
Closing -> Stale
