### ISSUE TITLE
Custom fields missing from the IssueType upon secondary runs.

### ISSUE THREAD

**Issue by ltakashvili** [tenable/integration-jira-cloud#297]
Hi

Sync was successful. I fixed several vulnerabilities of same plugin and when I run second sync I received error: `body=b'{"errorMessages":["\'transition\' identifier must be an integer"],"errors":{}}'`

```
[15:30:46] INFO     INFO:Processor:Building Task SQL Cache.                                        processor.py:152
           INFO     INFO:Processor:Building Subtask SQL Cache.                                     processor.py:158
[15:30:53] INFO     INFO:Processor:Finding related to Plugin 187315 is closed, skipping            processor.py:180
[15:30:54] ERROR    ERROR:restfly.errors.BadRequestError:[400: POST]                                   errors.py:91
                    https://adjara.atlassian.net/rest/api/3/issue/VULN-7510/transitions
                    body=b'{"errorMessages":["\'transition\' identifier must be an
                    integer"],"errors":{}}'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ltakashvili/test/lib/python3.12/site-packages/tenb2jira/cli.py:157 in sync                 │
│                                                                                                  │
│   154 │   │   │   │   │   │      jira_table(config)                                              │
│   155 │   │   │   │   │   │      ]))                                                             │
│   156 │   console.print(field_definition_table(processor.jira))                                  │
│ ❱ 157 │   processor.sync(cleanup=cleanup)                                                        │
│   158 │   if update:                                                                             │
│   159 │   │   with open(configfile, 'w', encoding='utf-8') as f:                                 │
│   160 │   │   │   tomlkit.dump(config, f)                                                        │
│                                                                                                  │


```
![image](https://github.com/user-attachments/assets/2c4d3e58-be3e-4805-98ca-256f92032fee)
when I visit transitions endpoints
![image](https://github.com/user-attachments/assets/3add6d4b-0aa9-428f-9d08-a3427dce9df2)

**Comment by SteveMcGrath** [comment]
Do you happen to have more of the traceback in question?

**Comment by ltakashvili** [comment]
> Do you happen to have more of the traceback in question?

I tried to troubleshoot it by myself and eventually in turned out that I didn't have enough permissions to transition from "To Do" --> "Done". Even when I browse web, I couldn't do it. I gained necessary permissions on my jira side and it went smooth.

But main issue that I currently have is that, when I run sync again, I am getting this infamous error messages

![image](https://github.com/user-attachments/assets/9fd6b9eb-28ef-419b-ab35-2f473245522c)

P.S I dont receive this error messages when I delete all ticket in jira and run sync again(with removed last_run)

I only receive this error when I fix some vuln and run sync command again. which is weird.

I have correct Task and sub-task IDs in config.toml

![image](https://github.com/user-attachments/assets/f0aaa0f4-9f80-4e1c-8883-69143e529962)
![image](https://github.com/user-attachments/assets/6fe2e72b-692b-413c-9326-2fabe05d1886)

checking task and subtask IDs in web. it seems IDs matches with config
![image](https://github.com/user-attachments/assets/5c765816-4a55-4882-8fb3-27a75a86aa51)
![image](https://github.com/user-attachments/assets/3a08d701-7c14-4838-8cf0-7897ac59cee5)

**Comment by SteveMcGrath** [comment]
can you run with the `--debug` flag set and let email me the full traceback & log?  smcgrath _at_ tenable.com

Also can you double check that the screens are configured?  that error is typically a mismatch in the issuetypes, but those looks good from what you have.

**Comment by ltakashvili** [comment]
> can you run with the `--debug` flag set and let email me the full traceback & log? smcgrath _at_ tenable.com
> 
> Also can you double check that the screens are configured? that error is typically a mismatch in the issuetypes, but those looks good from what you have.

Hi

I attached screenshots and also log files in email.

Also, very weird thing is that, during several syncs 2 subtasks were closed (which is correct, they are supposed to be closed they are fixed), but 2 is very low, there are more to be closed, but they aren't due to errors above

**Comment by SteveMcGrath** [comment]
So it appears that you have renamed the task and subtask issuetypes to something other than whats expected.  Also that neither issuetype is a subtask of the other.

```
│ │               'https://internalhost.atlassian.net/rest/api/3/issuetype/13737', 'id': '13737',    │ │
│ │               'description': 'Tenable Managed Vulnerability Issue Type', 'iconUrl':          │ │
│ │               'https://internalhost.atlassian.net/rest/api/2/universal_avatar/view/type/issuety… │ │
│ │               'name': 'Tenable Vulnerability', 'subtask': False, 'avatarId': 11500,          │ │
│ │               'hierarchyLevel': 0}, {'self':                                                 │ │
│ │               'https://internalhost.atlassian.net/rest/api/3/issuetype/13738', 'id': '13738',    │ │
│ │               'description': 'Tenable Managed Vulnerability Host Issue Type', 'iconUrl':     │ │
│ │               'https://internalhost.atlassian.net/rest/api/2/universal_avatar/view/type/issuety… │ │
│ │               'name': 'Tenable Vulnerability Host', 'subtask': False, 'avatarId': 11500,     │ │
│ │               'hierarchyLevel': 0}]
```

You could attempt to link them by adding the ID field to the relevent task and subtask definitions within the config file, however this is currently untested with issuetypes that arent parent-child related.

**Comment by SteveMcGrath** [comment]
Yeah looking into the debugs, its basically saying that none of the fields that were created are assigned to the screens associated to the subtask (10002), and that's where the failure is occurring.

If those fields ARE part of both of the screens, then it IS likely a permission issue, sadly Jira isn't very direct about what it's failing on when this happens.

Check that all of the permissions outlined here are applied to the user that is linked to the integration: https://github.com/tenable/integration-jira-cloud?tab=readme-ov-file#permissions

Looking through the log file I'm not seeing anything that points to something i can fix on my end.  I'd love to be wrong and get you something working, but we need to eliminate the permission and screen problems as potential issues first.

**Comment by ltakashvili** [comment]
> Yeah looking into the debugs, its basically saying that none of the fields that were created are assigned to the screens associated to the subtask (10002), and that's where the failure is occurring.
> 
> If those fields ARE part of both of the screens, then it IS likely a permission issue, sadly Jira isn't very direct about what it's failing on when this happens.
> 
> Check that all of the permissions outlined here are applied to the user that is linked to the integration: https://github.com/tenable/integration-jira-cloud?tab=readme-ov-file#permissions
> 
> Looking through the log file I'm not seeing anything that points to something i can fix on my end. I'd love to be wrong and get you something working, but we need to eliminate the permission and screen problems as potential issues first.

I checked and fields are assigned to screen associated to the subtask (10002)
But checked permissions and I found out that I didn't have permissions shown in README doc (edit issue and so on). I assigned all necessary permissions and everything went smooth. I think we can close this ticket :) 

Thanks a lot.

**Comment by SteveMcGrath** [comment]
Permissions in Jira has always been special.
