### ISSUE TITLE
Link tasks with subtask

### ISSUE THREAD

**Issue by jjagodzinski** [tenable/integration-jira-cloud#298]
Is it possible to link sub-task to task as "is child of" relation?

I would like to implement this kind of workflow:
Integration-jira-cloud creates task and sub-task with detected vulnerabilities. There is manual triage process to move sub-task to other projects in Jira. Other teams are working on repair detected vulnerabilities in their projects. Next scheduled scan checks if vulnerability was resolved. If yes, integration-jira-cloud add comment that task is fixed (because it cannot close task on another project).
When task and sub-task is linked, it will be easier to find all sub-task moved to other projects.

**Comment by SteveMcGrath** [comment]
So a couple of things here.

1. The current searching mechanism for keep tasks in sync doesn't support moving the task between projects. (hence why I assume you want to interlink tasks from other projects.
2. Is there any reason why an automation rule couldn't handle this when you link to a task within this project?

**Comment by jjagodzinski** [comment]
I had not considered the Jira automation tool to link tasks. In fact, this tool does what I need.
Would it be possible to extend the search mechanism to handle tasks moved to other projects? What I mean here is adding a comment that the vulnerability has been fixed, in a task that has been moved to another project.

**Comment by SteveMcGrath** [comment]
The problem with moving the search beyond the project its related to is that you make the permissions issues way more complicated, and the amount of lead-time to build the cache database would increase dramatically.  It's not something currently being considered.

**Comment by jjagodzinski** [comment]
Thank you for the clarification. I need to rethink this workflow.
