### ISSUE TITLE
Deleted assets in tenable.io

### ISSUE THREAD

**Issue by ltakashvili** [tenable/integration-jira-cloud#300]
Hi

I deleted some assets(via **"Explore Overview / Assets"** in tenable.io and run sync again but issues weren't closed in jira
Also, removed last_run parameter and run sync again, tickets still weren't closed in jira

I know this integration supports deleting subtasks with deadhosts, but I think it doesn't work well

**Comment by SteveMcGrath** [comment]
can you run again with `--debug` and report back with the log?  My own testing has proven successful.

**Comment by ltakashvili** [comment]
> can you run again with `--debug` and report back with the log? My own testing has proven successful.

done. sent via email

**Comment by ltakashvili** [comment]
I think I solved this issue. At first I had administrator role in tenable, changed to basic user and this issue emerged. changed back to administrator and solved this issue.

I think integration should check if I have necessary permissions before running sync

**Comment by SteveMcGrath** [comment]
Glad to hear you were able to address it, permissions checking is something thats roadmapped, but unsure when it'll work in.

If you use a non-admin user, you need to ensure that all of the permissions detailed in the readme are applied:

https://github.com/tenable/integration-jira-cloud?tab=readme-ov-file#permissions

**Comment by Higgsx** [comment]
> Glad to hear you were able to address it, permissions checking is something thats roadmapped, but unsure when it'll work in.
> 
> If you use a non-admin user, you need to ensure that all of the permissions detailed in the readme are applied:
> 
> https://github.com/tenable/integration-jira-cloud?tab=readme-ov-file#permissions

I meant permission issues in tenable, not jira. in tenable, I had basic user access and changed back to administrator role.
