### ISSUE TITLE
During the synchronization process, unauthorized information (tag information) was also synced to Jira.

### ISSUE THREAD

**Issue by echo54yu** [tenable/integration-jira-cloud#301]
We are using version 2.0.6 and have set up a synchronization account that is only authorized to sync certain assets to Jira, not other tag information. However, the account has accessed all tag information.   
This issue has arisen recently, although our configuration files have not been updated in months. Could there be any underlying design changes in Tenable?
<img width="397" alt="Information visible to the sync account_tag 2" src="https://github.com/user-attachments/assets/ef575dbc-c856-4baa-ba5e-6689589ced4b">
<img width="221" alt="Jira synced to many tags without authorization" src="https://github.com/user-attachments/assets/3fae80c9-7c4a-441e-9c5a-170f72ade3fc">

**Comment by echo54yu** [comment]
https://docs.tenable.com/release-notes/Content/vulnerability-management/2024.htm   
I have seen information posted here within the last seven days. Will this affect the synchronization of findings information?

**Comment by SteveMcGrath** [comment]
The integration will pull all tags for the filtered assets as provided by the API.  While the assets are filtered to specific tags, all tags associated to those assets will be returned.  The integration simply translates the related tags into Jira.

**Comment by echo54yu** [comment]
> The integration will pull all tags for the filtered assets as provided by the API. While the assets are filtered to specific tags, all tags associated to those assets will be returned. The integration simply translates the related tags into Jira.

So, all the vulnerabilities synced to JIRA will get all the tag information, right? Why were other tags not synced before this month?

**Comment by SteveMcGrath** [comment]
I can't answer that, as the integration is blindly reconstructing the tags from the asset export API.  There haven't been any changes to tag behavior since shortly after the rewrite.
