### ISSUE TITLE
Retrieve vulns with only tagged assets

### ISSUE THREAD

**Issue by ltakashvili** [tenable/integration-jira-cloud#302]
Hello

I know that in previous versions of the integration it had feature where we specify tags and only vulns with those tags were retrieved.
New integration changed that and this can be accomplished via access control permissions directly in tenable.io

I created new user with administrator role in tenable and assigned permissions to only retrieve vulns with tagged assets.
it worked great, but issue I have is in the below screenshot. tenable has default permissions where administators can view ALL assets

![image](https://github.com/user-attachments/assets/06ddfb02-0ebf-4819-8ea9-57cd9e7961e2)

because of this case, I have vulnerabilities in jira which doesn't have tags assigned to assets.

I tried to change user from administrator role to scan operator, basic user and so on, but issue is that only administrator can export assets. No other role can be used to retrieve assets. API call was /assets/export or something like this. only administrator can retrieve those.

any idea how can I solve this issue?

**Comment by SteveMcGrath** [comment]
The integration pulls ALL tags related to the associated assets as described from the Asset export API.  There currently is no way to filter that data down today.
