### ISSUE TITLE
Tenable-Jira Plugin Priority & Severity Match

### ISSUE THREAD

**Issue by PiusO** [tenable/integration-jira-cloud#304]
``Where, and how does one configure in Tenable Vulnerability Management/Jira, the matching of  Jira Priority to Tenable Severity, when it's pulled in?

Everything that comes in is set to medium currently.

Seen this floating around, but not sure where it goes, and what else to do -

`tenable:
  severity_prioritization:
    critical: 1
    high: 2
    medium: 3
    low: 4`

Using Jira Cloud - is this possible?

![image](https://github.com/user-attachments/assets/19205d1e-22a3-4490-a14e-3ae3ef7f1643)

![image](https://github.com/user-attachments/assets/e154cec5-752f-46d2-9094-072fd9d50ca3)

Thank you in advance

**Comment by PiusO** [comment]
I don't have access to a config file like I've seen in similar issues, maybe due to the Tenable product I'm using?

Is this something that automation in Jira can solve? if so any links, because I can't find anything?

**Comment by SteveMcGrath** [comment]
You are currently using the TVM in-product connector.  This project is a different integration altogether.  I'd suggest you contact tenable support:

https://docs.tenable.com/integrations/Atlassian/jira-cloud/Content/connect-tvm.htm

**Comment by PiusO** [comment]
Thanks for coming back Steve.

They told me it was Jira-Cloud field that was concerned so to go to Jira.

It's okay I think it's something that needs to be done with automation
