### ISSUE TITLE
Recasted Vulnerabilities are not being synchronized

### ISSUE THREAD

**Issue by Mohan1289** [tenable/integration-jira-cloud#305]
Hi,
I recast a specific plugin vulnerability severity from Info to Medium.
And ran the tenb2jira sync command to synchronize the vulnerabilities, but the recasted vulnerabilities were not created in Jira.

**Comment by SteveMcGrath** [comment]
The default behavior is to map to the default status, not the recasted one.  This was done for consistency reasons (what is the risk of the vulnerability task when you have 2 findings subtasks with different severities)

https://github.com/tenable/integration-jira-cloud/blob/main/tmpl_v1_conversion_config.toml#L547-L555

You CAN override that behavior however if you want it to work on both, you just need to add the `map_to_priority = true` flag to the severity as well:

https://github.com/tenable/integration-jira-cloud/blob/main/tmpl_v1_conversion_config.toml#L620-L627 

just add that line, just like you see it with the one above, and everything should work as you expect.  as the finding severity isn't configured fro the vulnerability task, it wont even be processed for use in the priority.  lastly as the last field in that list with the priority is the one that will stick, the severity priority will override the risk factor priority that was set earlier.

Hopefully that helps!

**Comment by SteveMcGrath** [comment]
No, the integration will still sync the state of the findings and vulnerability issues based on the computed finding id field.
