### ISSUE TITLE
Automating the script

### ISSUE THREAD

**Issue by dil-ddsouza** [tenable/integration-jira-cloud#31]
Hi Steve,

Hopefully this will be an easy one.

Where can I set the 'RUN_EVERY' variable please?  I know the observed-since option can be used whilst running the integration but not sure how to set the 'RUN_EVERY' option.

Also, is it the same as the service interval function within the config.yaml file? I tried setting that before, but didn't see it working. 

Thanks,

**Comment by SteveMcGrath** [comment]
RUN_EVERY is an environment variable.

This matches up to the following config file directive:

https://github.com/tenable/integration-jira-cloud/blob/master/example_config_file.yaml#L35-L41

**Comment by dil-ddsouza** [comment]
Thanks Steve, so when we set that interval, technically we have to leave the integration running right?

**Comment by SteveMcGrath** [comment]
correct.  The integration will run just the same as a one-off for the first time, then it will sleep itself for the specified number of hours and re-run using the timestamps of the last run as the starting point to pull deltas.

It was done this way to be easily dockerized and/or run as a service if desired.
