### ISSUE TITLE
All fields are not being populated

### ISSUE THREAD

**Issue by patelp132** [tenable/integration-jira-cloud#34]
Hi Steve,
A lot of the fields that are populated in tenable are not being pulled into JIRA. The Issue gets created with the field values set to "NONE" (See attached). Do you know why this might be?

Here is the config file:
```tenable:
  access_key: removed
  secret_key: removed
  tio_severities:
    - critical

jira:
  api_token: removed
  api_username: removed
  address: removed

project:
  leadAccountId: removed

issue_types:
  - jira_id: 3
    name: Task
    type: standard
    search:
    - Tenable Plugin ID
  - jira_id: 10000
    name: Sub-task
    type: subtask
    search:
    - Tenable Plugin ID
    - Tenable Asset UUID
    - Device IPv4
    - Device IPv6
    - Vulnerability Port
    - Vulnerability Protocol

screen:
  jira_ids:
    - 13365
    - 13366```

**Comment by patelp132** [comment]
<img width="243" alt="Screen Shot 2020-04-15 at 10 12 39 AM" src="https://user-images.githubusercontent.com/61480112/79368938-d30b5f00-7f15-11ea-9536-127cc5fbb6a4.png">
<img width="255" alt="Screen Shot 2020-04-15 at 10 12 18 AM" src="https://user-images.githubusercontent.com/61480112/79368948-d56db900-7f15-11ea-9317-e0554419b128.png">

**Comment by SteveMcGrath** [comment]
no idea at to why thats happening to be honest.  can you update to the latest version (1.1.4) and then run the integration with the `--troubleshoot` flag?

**Comment by patelp132** [comment]
Where am i adding the flag? im running ```tenable-jira -s --troubleshoot $(date -v-7d +%s) config.yaml```

**Comment by SteveMcGrath** [comment]
`tenable-jira --troubleshoot -s $(date -v-7d +%s)`

**Comment by patelp132** [comment]
```Usage: tenable-jira [OPTIONS] [CONFIGFILE]
Try 'tenable-jira --help' for help.

Error: no such option: --troubleshoot```

**Comment by SteveMcGrath** [comment]
Please update to the latest version (1.1.4)

https://pypi.org/project/tenable-jira-cloud/

**Comment by patelp132** [comment]
still getting the same error after downloading the update. Seems as when i try to run it keeps pulling the old version ```tenable-jira -s $(date -v-7d +%s) config.yaml                                                                            ✔  838  14:43:57
2020-04-15 14:44:35,343 root INFO Tenable2JiraCloud Version 1.1.3
2020-04-15 14:44:35,343 root INFO Using configuration file config.yaml
2020-04-15 14:44:35,349 root INFO Running on Python 3.7.7 Darwin/x86_64

**Comment by SteveMcGrath** [comment]
you may need for force the update.

**Comment by patelp132** [comment]
is there a way to update this or am i just pulling down the new version and using that? because the way i did this was install the new version and tried to run the command but getting the error of no such option

**Comment by SteveMcGrath** [comment]
`pip install --force -U tenable-jira-cloud`

**Comment by patelp132** [comment]
seems to keep reading the 1.1.3. what is the path of where the script will sit and be read from? might need to go remove that and reinstall

**Comment by SteveMcGrath** [comment]
are you still stuck with 1.1.3?  I'm assuming whatever cache you may have been hitting on PyPI is likely refreshed by now

**Comment by patelp132** [comment]
yeah its still stuck on 1.1.3. not sure where the script is being read from because i was trying just clear everything up and do a reinstall entirely but it still keeps reading the 1.1.3 release

**Comment by SteveMcGrath** [comment]
you can always manually download the latest release from here and manually apply using `pip install /path/to/package`

https://github.com/tenable/integration-jira-cloud/releases/tag/1.1.4

**Comment by patelp132** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/tenable-jira", line 5, in <module>
    from tenable_jira.cli import cli
  File "/Users/parth.patel/Library/Python/2.7/lib/python/site-packages/tenable_jira/cli.py", line 182
    print(output, file=reportfile)

**Comment by patelp132** [comment]
I tried to go back to 1.1.3 but now i'm seeing 

```Traceback (most recent call last):
  File "/Users/parth.patel/Library/Python/2.7/bin/tenable-jira", line 5, in <module>
    from tenable_jira.cli import cli
  File "/Users/parth.patel/Library/Python/2.7/lib/python/site-packages/tenable_jira/cli.py", line 26, in <module>
    from tenable.io import TenableIO

**Comment by SteveMcGrath** [comment]
Python 2 isn't supported as mentioned in the README.

**Comment by patelp132** [comment]
I have python 3.7 installed. Not sure why when i do an install or an update things are being placed into those directories

**Comment by SteveMcGrath** [comment]
Likely an issue of having multiple pythons installed.  May I suggest you look into pyenv and pyenv-virtualenv?  As your on a Mac, both can be installed via homebrew and they will solve for your ambiguity issues.

https://github.com/pyenv/pyenv

**Comment by patelp132** [comment]
Got it. But when running the script it gets stuck at this point:
```RetryError ERROR POST https://cloud.tenable.com/vulns/export >> 6 attempts made, last returned 445eb6d2b88639e6ec4379d409c245a3:504 {"statusCode":504,"error":"Gateway Timeout","message":"Please wait a moment and try your request again."}
Traceback (most recent call last):
  File "/usr/local/bin/tenable-jira", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tenable_jira/cli.py", line 185, in cli
    ingest.ingest(observed_since)
  File "/usr/local/lib/python3.7/site-packages/tenable_jira/transform.py", line 459, in ingest
    num_assets=self.config['tenable'].get('chunk_size', 1000))
  File "/usr/local/lib/python3.7/site-packages/tenable/io/exports.py", line 285, in vulns
    'vulns/export', json=payload).json()['export_uuid']
  File "/usr/local/lib/python3.7/site-packages/tenable/base.py", line 561, in post
    return self._request('POST', path, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tenable/base.py", line 525, in _request
    raise RetryError(resp, retries)
tenable.errors.RetryError: 6 attempts made, last returned 445eb6d2b88639e6ec4379d409c245a3:504 {"statusCode":504,"error":"Gateway Timeout","message":"Please wait a moment and try your request again."} ```

Running the latest release 1.1.5

**Comment by SteveMcGrath** [comment]
I would attempt to run the integration again, and if you continue to see 504 errors, thats an issue unrelated to the integration and we'll have to handle that differently.

**Comment by patelp132** [comment]
Yup, seeing the 504 still. Not sure what it is attempting to do and its unreachable

**Comment by SteveMcGrath** [comment]
Do me a favor then, open a support issue with Tenable proper, Tell them you'r having issues with the vuln export APIs and reference this github ticket.

**Comment by patelp132** [comment]
submitted a ticket. Do you think this can be an auth issue? have you seen others having the same issue? It was working fine Monday morning and then when i tried to run it again later the same day.  It started giving this error

**Comment by SteveMcGrath** [comment]
Thats typically an issue with the export service within Tenable.io, and not anything you did.
