### ISSUE TITLE
is it possible to run this using aws lambda?

### ISSUE THREAD

**Issue by dilenday** [tenable/integration-jira-cloud#35]
Is it available to run this script on AWS Lambda? I'm interested to create a cron job on Lambda and whether it will work to run the cron job, which would run the **sudo tenable-jira** every week for example on my host.

I think it's doable, but don't know for sure, any suggestions whether it will work okay?

**Comment by SteveMcGrath** [comment]
While it should work, I'm not very lambda-savy.  You would likely want to store the time of the last run and pass that with since.  If you're willing to report back what you have done, I'd be happy to reference this ticket in the readme and add it for others to leverage as well.

**Comment by codebop** [comment]
@dilenday Did you end up doing this? I'd like to do the same thing.
