### ISSUE TITLE
inport Tags for SC and IO

### ISSUE THREAD

**Issue by r1ckyb0nd** [tenable/integration-jira-cloud#36]
Is it possible to edit the script to bring in the asset tags in SC and IO. This will help with sorting and searching.

**Comment by SteveMcGrath** [comment]
SC is a definite no-go.  The APIs around interlinking vuln data with asset lists isn't scalable in that way.  It would dramatically slow down the integration and create a lot of churn on the SC instance.

IO on the other hand is now exporting the tagging data in the asset export API.  Leveraging this would require doing an asset export and caching the data in beforehand.  Definately doable, but it isn't a simple "just add this field".
