### ISSUE TITLE
Already Existing Key and Name

### ISSUE THREAD

**Issue by cc-vyessa** [tenable/integration-jira-cloud#40]
We use Jira Cloud and Tenable.io.  I have a project created for vulnerabilites that I have been using to create manual tickets.  Issue is that I used the same Project Name and the same VULN key when i created that years ago.  I tried to change it in my project, but it that does not free up the original key -- looks like Jira saves it in their db.  I get a key already exists error.  I can try some stuff to see if I can somehow get that key recovered, but it seems like it would be good functionality to let the user specify the key and project name.

**Comment by SteveMcGrath** [comment]
Just specify the key param in the project stanza right next to the lead account.

```yaml
project:
  key: NewKey
```

**Comment by cc-vyessa** [comment]
Thought so.  Thanks!
