### ISSUE TITLE
Only pull VPR score higher than n  ?

### ISSUE THREAD

**Issue by MichaelTay0** [tenable/integration-jira-cloud#41]
Is there a way in the config file to only pull in vulnerabilities that surpass a certain VPR score threshold?

For example, I only want the integration to pull in vulnerabilities with a VPR score higher than 7.0

**Comment by SteveMcGrath** [comment]
currently not in the code, however can be added.

**Comment by SteveMcGrath** [comment]
@MichaelTay0 so you are aware that because VPR scores may change over time, it is possible for an issue imported to get "orphaned" if the VPR score drops below the threshold?

**Comment by MichaelTay0** [comment]
Yes, I am aware. In our current workflow, we want to automate the more critical / threat worthy vulns. we still have a manual process in place to address the other stuff. essentially we are using the integration to populate all the ticket work lol. and then linking tasks and subtasks into other boards. 

Has this change been added? 

would `tio_vpr_thresh: n` work for the config?

**Comment by SteveMcGrath** [comment]
has not been released in a version yet, but is in the repo.  if you want to test it, pull from master on GH.

**Comment by SteveMcGrath** [comment]
as for how to use, you would do the following:

```yaml
tenable:
  tio_vpr_thresh: 7.0
```

**Comment by SteveMcGrath** [comment]
Exists in current release now.
