### ISSUE TITLE
Upgraded to 1.1.6 and received the following error. NameError: name 'tio' is not defined

### ISSUE THREAD

**Issue by MichaelTay0** [tenable/integration-jira-cloud#42]
`File "/usr/local/bin/tenable-jira", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tenable_jira/cli.py", line 109, in cli
    if int(tio.sessions.details().get('permissions')) < 64:
NameError: name 'tio' is not defined`

**Comment by SteveMcGrath** [comment]
*sigh*. i did a stupid

**Comment by SteveMcGrath** [comment]
1.1.7 released using `source` for the source point instead of `tio` like i do everywhere else >.<

**Comment by MichaelTay0** [comment]
haha all good. but now im getting...  
if int(source.sessions.details().get('permissions')) < 64:
AttributeError: 'TenableIO' object has no attribute 'sessions'

**Comment by SteveMcGrath** [comment]
-_-  I should drink more coffee before working on code...

**Comment by SteveMcGrath** [comment]
I have corrected my previous errors.  This one tested ok. should be good.

**Comment by MichaelTay0** [comment]
Thank you sir. updated to 1.1.8 and looks to be working

**Comment by SteveMcGrath** [comment]
fantastic.  so lesson learned, do not commit code until at least 2 cups of coffee have been consumed ;)
