### ISSUE TITLE
Issue Type Errors preventing creation of Jira tickets

### ISSUE THREAD

**Issue by DoomSeeker66** [tenable/integration-jira-cloud#50]
We were able to get the plugin installed and we actually got it to generate one ticket, but then it stopped and presented us with a "Issue type Error". we have gone back an verified the issue type internal IDs for task and sub task and explictly set them in the config. Our Jira instance is pretty cluttered so it could be the result set is ambigous which is why its not finding things correctly. Using the test script provided in the tenable github repo I see many results for the task and subtask issue types. Does anyone have a way to help the plugin navigate a cluttered Jira instance? thank you
![image](https://user-images.githubusercontent.com/66316272/83527446-d05ccd00-a4b5-11ea-82b6-40e2af24a4e7.png)

**Comment by SteveMcGrath** [comment]
I sadly don't have a good answer for you.  You can hard-code the issuetypes once you know what they are, however you're going to have to figure out what are the _right_ issuetypes first.
