### ISSUE TITLE
Question: Can we customize the Jira tasks to contain Hosts and subtasks to pluginId?

### ISSUE THREAD

**Issue by Tulasi-Pilli** [tenable/integration-jira-cloud#51]
"Task for each Vulnerability and creates each vulnerability instance as a Sub-task". 
1. Instead, can we customize Task with vulnerability instance(IP address) and Subtask with vulnerabilities of all severities associated with an instance?
2. Can we pull hostname instead of IP Address?
3. If I've created SOME jira tickets manually from a scan ran today, does this configuration create duplicates if I set the -s, --observed-since option to today?

**Comment by SteveMcGrath** [comment]
That workflow would require a completely different config file.  While possible, its untested and therefore unsupported.  You could contact Tenable's professional services team for assistance there.
