### ISSUE TITLE
Since in Windows

### ISSUE THREAD

**Issue by cc-vy** [tenable/integration-jira-cloud#52]
How would you use the  -s since option on a Windows device ?

**Comment by SteveMcGrath** [comment]
same as on a linux device?

**Comment by cc-vy** [comment]
Not quite.  The string you provided as an example does not work on windows. 

Verónica Yessa | Senior Security Analyst
Chapman and Cutler LLP
111 West Monroe Street | Chicago, IL 60603
Direct: 312.845.3015
vyessa@chapman.com

**Comment by SteveMcGrath** [comment]
it should just work.  if it's not, it might be a pathing issue.  Have you considered looking into where your python bins are installed?

Also, you had exposed your email in the signature by replying via email.  I had edited it out.

**Comment by cc-vy** [comment]
ok will check and thanks.
