### ISSUE TITLE
Question regarding shutdown assets for SC.

### ISSUE THREAD

**Issue by dil-FBond** [tenable/integration-jira-cloud#57]
I understand in IO when you remove an asset from the asset inventory, all sub-tasks meant for that asset are closed. How does this work for SC?
From what we can tell is the sub-tasks stay open in JIRA even when there is nothing in Tenable.SC. 

Additionally, we are noticing a lot of sub-tasks in JIRA that are not in Tenable.sc in either open or mitigated. 

Is there a way to have the script close any open sub-task that does not match up to an open Tenable.SC vulnerability?

**Comment by SteveMcGrath** [comment]
The Tenable.sc queries rely on vulns that are a patched state within SC:

https://github.com/tenable/integration-jira-cloud/blob/master/tenable_jira/transform.py#L623-L632

In short, SC is informing the integration that the state is now closed for those vulns.

**Comment by dil-FBond** [comment]
This means when a asset in Tenable.sc is removed because of not being scanned either once or after XXX days, all the Vulnerabilities will be ghosts in JIRA?

Additionally, does the process of tenable.io when you remove an asset closes the vulnerability work for both scanner scans and agent scans?

Rick

**Comment by SteveMcGrath** [comment]
For IO, termed and deleted assets will have the associated issues removed:

https://github.com/tenable/integration-jira-cloud/blob/master/tenable_jira/transform.py#L569-L608

For SC, if a vuln ages out in the platform, then it's an orphaned issue.  There isn't any indicator from SC to tell the integration to remove it.  The assumption there is that in a healthy VM program, that should be fairly infrequent, and shouldn't be an issue.  If that isnt the case, then you could simply mass-delete any issues with a last seen date of over X days within jira.
