### ISSUE TITLE
Tenable.io - Jira: Creating duplicate issues (Vulnerabilities) for the same host with different IPs

### ISSUE THREAD

**Issue by dil-ddsouza** [tenable/integration-jira-cloud#59]
Hi Steve,

We yesterday noticed, that the tenable.io - Jira integration was creating duplicate vulnerabilities for a host that has dynamic IPs. 

**Background:** We installed a tenable agent on of our test machines in order to see how we can use tenable.io for vulnerability management. 

**Isssue:** We noticed that the vulnerbilities were marked as mitigated in tenable.io but were not being marked as 'Done' in Jira. Here is an example where the integration created 3 duplicate vulnerbilities for the same host but different IPs:

![image](https://user-images.githubusercontent.com/61977548/85393989-cf174100-b545-11ea-9124-f5bc0cf3bb17.png)

Have you seen this before? It looks like it is classing every IP as unique instead of the hostname or netbios. Hence creating duplicate vulnerabilities for every dynamic IP assigned to that host. Also, we noticed that it doesn't mark issues as done even though they are mitigated in Tenable.io.

Any help would be appreciated

Thanks,

**Comment by SteveMcGrath** [comment]
You'll likely want to modify the searching logic in your config file.  The default looks for both UUID and IP.  you'll want to remove the IP constraints and save it in your .conf file.

https://github.com/tenable/integration-jira-cloud/blob/master/tenable_jira/config.py#L103-L117

**Comment by dil-ddsouza** [comment]
Perfect! thank for this Steve. I have tested this out and it seems to do the job.
