### ISSUE TITLE
 Integration JIRA Cloud results in no content from Tenable.io

### ISSUE THREAD

**Issue by evazquez00** [tenable/integration-jira-cloud#61]
Brand new install of the JIRA integration from https://github.com/tenable/integration-jira-cloud

(Full functionality of the plugin was guaranteed by our Sales Rep and Customer Success Manager.)

The setup utility created the project and key as expected, but when trying to retrieve information from our account, a '200 None' code is returned.

2020-08-04 08:59:59,543 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "POST /vulns/export HTTP/1.1" 200 None

There are over 160 Criticals and 1600+ High vulnerabilities in our dashboard, so I know that the above is not correct.

Command line to create /poll the project was:
$ python3 --version
Python 3.8.5
$ pip --version
pip 20.2.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
$ pip show tenable-jira-cloud
Name: tenable-jira-cloud
Version: 1.1.11
Summary: Tenable -> Jira Cloud Bridge
Home-page: https://github.com/tenable/integrations-jira-cloud
Author: Tenable, Inc.
Author-email: smcgrath@tenable.com
License: MIT
Location: /home/evazquez/.local/lib/python3.8/site-packages
Requires: pytenable, restfly, arrow, Click, pyyaml
Required-by: 
$
$ tenable-jira --troubleshoot SageSure/jira-tenable.yaml

Content of "SageSure/jira-tenable.yaml is:

tenable:
access_key: <REDACTED>
secret_key: <REDACTED>

jira:
api_token: <REDACTED>
api_username: <REDACTED>
address: <REDACTED>

project:
name: InfoSec Vulnerability Mgt
leadAccountId: <REDACTED>

Redacted DEBUG file:
[issue_debug.md](https://github.com/tenable/integration-jira-cloud/files/5023498/issue_debug.txt)

**Comment by SteveMcGrath** [comment]
Looks like you have requested only vulns that are newer than "Tue Jul 28 14:20:47 2020 UTC" with the timestamp of 1595946047.  That might be the underlying cause.

**Comment by evazquez00** [comment]
Last scans were run between Aug 1 2200/UTC and Aug 3 0430/UTC,

Dashboard shows 964 devices scanned in the past 7 days, with a fair few existing, new and resurfaced vulnerabilities discovered, so there should be results when the plugin polls the TIO interface.

My command line had a "-s" on first run, but as above, not on second run (e.g. I decided make sure I was pulling in everything).  The debug file is from the second run, so maybe it kept the setting somewhere?

I'll run whatever other debug /trace you need to help me figure this out...

**Comment by SteveMcGrath** [comment]
Do you have the `SINCE` env var set?

**Comment by evazquez00** [comment]
Not anywhere I can find (or have deliberately set).

**Comment by SteveMcGrath** [comment]
well looks like your using a unix prompt.  you can always check using:

```shell
set | grep SINCE
```

and then to unset it its:
```shell
unset SINCE
```

It's the only place where the integration could potentially pull that parameter from what I am seeing.  You didn't set it in the config file (at least from whats in the debug).  You can also forcibly set it to something like 30 days using:

```shell
tenable-jira -s $($(date -v-30d +%s) SageSure/jira-tenable.yaml
```

If that works, I'd recommend setting it up on a separate VM or docker container and add the following to the config to have it run as a service:

```yaml
service:
  # How many hours between runs
  interval: 24
```

**Comment by evazquez00** [comment]
OK, gave all that a shot - but there is still no joy in Mudville...

I ran it twice - once with the variable defined (which seems to work just fine), once with the timestamp explicitly set to cross-check.

Both runs still return "200 None".

`$ set SINCE`
`$ `
`$ date -v-30d +%s`
`date: invalid option -- 'v'`
`Try 'date --help' for more information.`
`$ date -d '-30 day'`
`Mon 06 Jul 2020 09:21:41 AM MDT`
`$ date -d '-30 day' +%s`
`1594048826`
`$ echo $(date -d '-30 day' +%s)`
`1594048826`
`$ tenable-jira -s $(date -d '-30 day' +%s) --troubleshoot ./SageSure/jira-tenable.yaml`
`$ tenable-jira -s 1594048826 --troubleshoot ./SageSure/jira-tenable.yaml`

[issue_debug_unixtimestamp-20200805.txt](https://github.com/tenable/integration-jira-cloud/files/5029367/issue_debug_unixtimestamp-20200805.txt)
[issue_debug_variable-20200805.txt](https://github.com/tenable/integration-jira-cloud/files/5029368/issue_debug_variable-20200805.txt)

**Comment by evazquez00** [comment]
More troubleshooting - I decided to expand the vulnerabilities list by adding:

`  tio_severities:`
`    - critical`
`    - high`
`    - medium`
to the "tenable:" section in my config file, which resulted in:

`2020-08-05 09:53:31,263 tenable.io.TenableIO DEBUG {"method": "POST", "url": "https://cloud.tenable.com/vulns/export", "params": {}, "body": {"filters": {"last_found": 1594050801, "severity": ["critical", "high", "medium"]}, "num_assets": "1000"}}`

within the debug file.

Yet it still returns "200 None" for the query.

**Comment by evazquez00** [comment]
Yet more futzing around by me.  I completely removed the PIP install of tenable-jira and removed all directories under ~/.local.

I built and installed from Git Clone and ran it - same result.

Un-installed, cleaned out ~/.local again and re-installed with PIP.

Even as clean as I can make it on my local system, it still returns "200 None" to the export query.

**Comment by SteveMcGrath** [comment]
something is really off here.  I cant replicate your experience on my own.  Are you open to hopping on a web meeting?  We can move this off public github, feel free to email me smcgrath@tenable.com
