### ISSUE TITLE
Tickets for Vulnerabilities No Longer There

### ISSUE THREAD

**Issue by cc-vy** [tenable/integration-jira-cloud#62]
I am seeing tasks being created for vulnerabilities that are no longer present on the asset in question.  The ticket shows Vulnerability Last Seen Jan 22, 2020, 11:24 PM.  I checked the asset, and it is not there.   Tried closing it, but it just gets recreated next time it runs. 

I have debugging on, but I have no idea what to check.

**Comment by SteveMcGrath** [comment]
did you specify a since parameter?  are you running it as a service?

**Comment by cc-vy** [comment]
it's running every 24 hours with the service interval: 24 setting.  That works fine, no issues there.

**Comment by cc-vy** [comment]
Any thoughts on why this might be happening or things i can check?

**Comment by SteveMcGrath** [comment]
were the hosts deleted?  have the hosts simply gone away?

**Comment by cc-vy** [comment]
No, not deleted and not simply gone away.  Still there and when checking the asset view in Tenable.io, without the vulnerabilities that keep re-opening or not closing.

**Comment by SteveMcGrath** [comment]
That is odd, as the integration is relying on what IO is telling it to do.  I get the impression this is going to require a web meeting to root out whats going on here.  Hit me up at smcgrath _at_ tenable.com.

**Comment by limitup** [comment]
I see this same issue.  I have attributed it to the asset list.  If there is an asset name change or an update to the agent the asset inventory changes.  You might have two assets with the same name, the vulnerabilities are most likely tied to the older asset.  I found that If the duplicate asset is removed, the tickets get closed.

**Comment by cc-vy** [comment]
I have another example of a vulnerability that gets a new ticket when i close the existing  one.  The odd thing on this one, unlike the other, is that if I search for the asset in tenable.io by using a hostname/ip address filter or even the uuid filter in the assets dash, it does not show up.  If i use the UUID that is in the ticket info and plug that in to the URL of an asset, I can see it, though.  It has no associated vulnerabilities and was last seen August 1st.  I do not recall deleting assets then, but even if i had, they should still show since Tenable will not drop anything until last seen 90 days.

**Comment by SteveMcGrath** [comment]
If you delete the asset in IO, then it should auto-close from there.

**Comment by cc-vy** [comment]
But i did not delete this or the others.   I will try to delete this ghost one now, though, and see what happens.

**Comment by SteveMcGrath** [comment]
It should remove it.  The integration pulls the terminated and deleted assets and should close them.

**Comment by cc-vy** [comment]
That worked for this one!

**Comment by cc-vy** [comment]
I found another example, though, of an asset that is there, not deleted, no longer shows the vulnerability, but the ticket gets recreated if I close it.

**Comment by SteveMcGrath** [comment]
can you describe how specifically you are running the integration?

**Comment by cc-vy** [comment]
I am not sure what you mean.  I have no issues running this.  For the most part, it seems to work fine.  I have tried to run this by hand and also as a service.  Regardless of how i run it, if i close one of these tickets, the next run opens a new one. Other than than, it runs fine.  It just opens vulnerabilities that are not there on the tenable side for certain assets.  I am not sure how the way I run this could cause it, but if you tell me what specifically you need to know about how it runs maybe i can answer that better.

You had asked for a screenshare.  Let me know when you can do that - i am generally available between 9 am and 5 pm central except tomorrow.

**Comment by SteveMcGrath** [comment]
Looks like time got away from me a bit, as mentioned earlier in this thread, lets take screenshare & timing information into email.  smcgrath _at_ tenable.com

**Comment by cc-vy** [comment]
I just sent you another email.  Letting you know in case you are not receiving them for some reason.

**Comment by SteveMcGrath** [comment]
Responded.  First one seemed to have been lost in the shuffle.

**Comment by SteveMcGrath** [comment]
Addressed as an issue with vuln aging, not the integration itself.
