### ISSUE TITLE
Set jira ticket priority to match vulnerability priority in tenable

### ISSUE THREAD

**Issue by tpinckard** [tenable/integration-jira-cloud#65]
I realize that we can access the vulnerability priory by checking out the Vulnerability Severity, under vulnerability.

It would sure be neat if the Jira ticket priority was set to match the priority of the vulnerability found in tenable.io, instead of creating all tickets using the same jira priority.

**Comment by evazquez00** [comment]
Perhaps set the behavior as an option in the YAML (so others aren't forced down our path)?

Agreed, it would be nice to sort /prioritize based on Tenable Severity.

**Comment by SteveMcGrath** [comment]
This is now optionally possible through some minor config edits as if 1.1.14.  You will need to inform the integration of prioritization IDs to use for each severity classification.  For example, I added the `severity_prioritization` values below in my test instance with success:

```yaml
tenable:
  severity_prioritization:
    critical: 1
    high: 2
    medium: 3
    low: 4
```

Supporting it in this way allows you guys to specify what priority state to push the vulns into based on severity.  entirely your choice ;)
