### ISSUE TITLE
"Appropriate screen, or unknown" error

### ISSUE THREAD

**Issue by Clickbaitcake** [tenable/integration-jira-cloud#67]
When running the integration from Tenable.io to Jira cloud I get the following error.  Am stuck on how to fix or workaround other than completely deleting the project and its internals.

`customfield_10259":"Field \'customfield_10259\' cannot be set. It is not on the appropriate screen, or unknown."`

From the script log (In warn mode)
`2020-09-02 11:17:06,990 restfly.errors.BadRequestError ERROR [400: POST] https://ABC.atlassian.net/rest/api/3/issue?update_history=False body$`

Is this an issue with the integration not mapping fields correctly similar to the other common problems listed on the Read Me?

**Comment by SteveMcGrath** [comment]
can you please submit the output of a `--troubleshoot` run?

**Comment by kidshay** [comment]
[tenable_debug_old.log](https://github.com/tenable/integration-jira-cloud/files/5203724/tenable_debug_old.log)

please see attach I am having the same issue.

**Comment by SteveMcGrath** [comment]
@kidshay your issue appears to be one of a screen selection issue.  Refer to https://github.com/tenable/integration-jira-cloud/issues/23#issuecomment-604631753

**Comment by Clickbaitcake** [comment]
Hello @SteveMcGrath 

When I run: `tenable-jira config.yaml --troubleshoot` I get back: `Error: no such option: --troubleshoot`
What am I doing wrong?

Thank you!

**Comment by SteveMcGrath** [comment]
@Clickbaitcake what version are you running?

**Comment by SteveMcGrath** [comment]
Closing per request
