### ISSUE TITLE
Question in regards to integration

### ISSUE THREAD

**Issue by valterebizh** [tenable/integration-jira-cloud#71]
Right now we have it configured but it seems to only pull Severe and High severity level alerts - what do we do so that it pulls all alerts? 

this is from the config.py file. anything that i should change here? or 

```
  # Tenable.io vulnerability severities to convert to JIRA tickets.
  tio_severities:

```
i also see this in the config.yaml file

```
  # What is the logging level desired?  Available levels are:
  # debug, info, warn, error
  # The default level if unspecified is "warn"
  level: warn
```

Anything to do here? 

Thanks in advance, hope i make sense.

**Comment by SteveMcGrath** [comment]
I'd caution you from pulling everything, however if thats the intent:

```yaml
tenable:
  tio_severities:
  - critical
  - high
  - medium
  - low
```

If you want to see more log messages, then set the log level differently:

```yaml:
log:
  level: info
```

**Comment by valterebizh** [comment]
Hey Steve, thank you so much - yep this is what the guys want. I'll update the configs with your suggestions, much appreciated. Thanks for building all of this out it works wonderfully. 

VT
