### ISSUE TITLE
Feature Request :: Transform a Tenable Tag into a Jira Field

### ISSUE THREAD

**Issue by ridoline** [tenable/integration-jira-cloud#76]
I was wondering if it would be possible to add the ability to transform a Tenable Tag into a Jira Field Value

In Example:
1) Within the tenable environment we configure a tag on assets named "Component", the value of which is the service component that that asset relates to.
2) Upon syncronization,  The Value within Component will be set for the Subtask.

I could see this being very powerful, because as of right now there is no way to translate business context that might be stored within Tenable to tickets within Jira.    In our instance we are both new to utilizing Jira and Tenable, so if there is an alternative approach that someone could suggest, I think it would help immensely

**Comment by SteveMcGrath** [comment]
Definitely possible.  Even possible today with just some work in the config.  Follow the instructions linked below:

https://github.com/tenable/integration-jira-cloud/issues/69#issuecomment-691196283

And here is an example config

https://github.com/tenable/integration-jira-cloud/issues/70#issuecomment-700242929

**Comment by ridoline** [comment]
Not sure what you mean

Would you mean something like this might work given that I get the field types right?

- issue_type:
  - Sub-task
  jira_field: Components
 searcher: textsearcher
  tio_field: asset.tags["Components"]
  type: readonlyfield

**Comment by ridoline** [comment]
After some experimentred I ended up having to add the following to accomplish what I wanted:




`diff --git a/tenable_jira/transform.py b/tenable_jira/transform.py
index 09023cd..54ca74b 100644
--- a/tenable_jira/transform.py
+++ b/tenable_jira/transform.py
@@ -572,6 +572,8 @@ class Tio2Jira:

                 # iterate over the tags
                 for tag in asset['tags']:
+                    if tag['key'] in self.config['tenable'].get('tio_asset_tag_attr_cache_transform',list()):
+                        self._asset_cache[asset['id']][tag['key']] = tag['value']
                     # Generate the tag name to use.
                     tag_name = '{key}:{value}'.format(
                         key=tag['key'],
`

I then updated the config to include
  tio_asset_tag_attr_cache_transform:
    - component
  tio_asset_attr_cache:
    - component

There was likely a more elegant approach, however I just wanted to understand if it was possible and as I was review the code, I slapped this together
