### ISSUE TITLE
Question: Retrieve full list of available Tenable.io fields from an asset /vulnerability

### ISSUE THREAD

**Issue by evazquez00** [tenable/integration-jira-cloud#77]
I had an internal request to begin tagging priority based on the relatively new Tenable.io VPR score.

Not seeing this score directly listed in my Tenable.io instance for either assets or vulnerabilities, I'm wondering if there's a way to query all retrievable fields and their pyTenable stanza identifiers so that I can experiment a bit (or verify that this exists, if new or other fields exist, etc.)?

**Comment by SteveMcGrath** [comment]
VPR is on assets.  While not all vulns have a VPR score, if it does it should already be picked up by the integration.

https://github.com/tenable/integration-jira-cloud/blob/master/tenable_jira/config.py#L458-L465

In any case, a good example is here:

https://developer.tenable.com/reference#exports-vulns-download-chunk

If you look at the response, the vpr score would end up being `plugin.vpr.score`.
