### ISSUE TITLE
getting error tenable-jira config.yaml

### ISSUE THREAD

**Issue by dheerajthapa** [tenable/integration-jira-cloud#78]
<pre>(cloud-jira) [centos@centos8 ~]$ tenable-jira ~/cloud-jira/config.yaml
Traceback (most recent call last):
  File &quot;/home/centos/cloud-jira/bin/tenable-jira&quot;, line 11, in &lt;module&gt;
    load_entry_point(&apos;tenable-jira-cloud==1.1.15&apos;, &apos;console_scripts&apos;, &apos;tenable-jira&apos;)()
  File &quot;/home/centos/cloud-jira/lib64/python3.6/site-packages/click/core.py&quot;, line 829, in __call__
    return self.main(*args, **kwargs)
  File &quot;/home/centos/cloud-jira/lib64/python3.6/site-packages/click/core.py&quot;, line 782, in main
    rv = self.invoke(ctx)
  File &quot;/home/centos/cloud-jira/lib64/python3.6/site-packages/click/core.py&quot;, line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File &quot;/home/centos/cloud-jira/lib64/python3.6/site-packages/click/core.py&quot;, line 610, in invoke
    return callback(*args, **kwargs)
  File &quot;/home/centos/cloud-jira/lib64/python3.6/site-packages/tenable_jira/cli.py&quot;, line 66, in cli
    fields = config_from_file.pop(&apos;custom_fields&apos;)
KeyError: &apos;custom_fields&apos;
(cloud-jira) [centos@centos8 ~]$ 

</pre>

**Comment by SteveMcGrath** [comment]
This was a stupid bug as no default list value was set if custom_fields were unspecified.  1.1.16 has this addressed.
