### ISSUE TITLE
Feature Request: Map Tenable vulnerability severity with JIRA priority

### ISSUE THREAD

**Issue by aaralekar** [tenable/integration-jira-cloud#79]
Hello Tenable,

We are currently using Tenable JIRA integration to create tickets in JIRA, but the vulnerability priority in tenable doesn't exactly match with JIRA priority. We would like to have that priority matching between Tenable and Jira. Following is the mapping between Tenable severity and JIRA priority that we would like to see - 

     Tenable severity              JIRA priority
1.    Critical ---------------- 0 (Showstopper)
2.    High ------------------ 1 (High)
3.    Medium ---------------2 (Medium)
4.    Low ------------------ 3 (Low)

Currently both Critical and High severity tickets are being assigned "High" priority in JIRA.
Please let us know if this is something that's feasible to achieve.

Thanks

**Comment by SteveMcGrath** [comment]
https://github.com/tenable/integration-jira-cloud/issues/65#issuecomment-691186805
