### ISSUE TITLE
Transform Tenable Tag to Jira Variable

### ISSUE THREAD

**Issue by ridoline** [tenable/integration-jira-cloud#80]
Hello,

I'd like the ability to transform a specific Tenable tag into a Names Variable in Jira

For Example a Tag Component:Active Directory, I would like to set Component = Active Directory in Tenable.

I had opened this ticket previously, however prior to responding it was closed.

**Comment by SteveMcGrath** [comment]
This would require some significant code changes to support.  If this is desired, then you may want to discuss this with Tenable Professional Services.

**Comment by ridoline** [comment]
I did open a ticket with Tenable and they said to post here.   I have made it work and gave an overview of how I made it work in my previous post.   https://github.com/tenable/integration-jira-cloud/issues/76. I'm assuming that because you closed this ticket you also won't see this response.

**Comment by SteveMcGrath** [comment]
I do see the response, and while that approach does indeed work, I do have some concerns with the approach in #76, and I was away on PTO last week so I didn't get to any of this until today.  Some of the main issues revolve around the case sensitivity of tags, and how to best approach them.  Currently "Component" != "component" for example.  Also this allows for the asset attributes sub-object to really balloon, which concerns me when it comes to memory usage for larger installations.

**Comment by ridoline** [comment]
Would the memory considerations be the same based upon the number of asset attributes that are configured?  in the example provided I utilized the same asset cache stanza to identify tags that I'd like to transform into the asset cache.   

My perception is that this is likely more valuable to us, then being able to syncronize say mac address, as this would allow for the business context information that would drive remediation to be syncronized.  Otherwise we will need to figure out another approach to assign work to individuals and groups which will be far more challenging if we cannot synchronize the business context provided by Asset Tags.   

The challenge with Asset tags as it stands in the way they are synchronized currently is related to the field type.  The label field provides little capability to split the name/value pairs once they are within Labels, and we cannot fuzzy match or complete regexp against these values once they are within Jira.
