### ISSUE TITLE
Asset info not populating in Jira

### ISSUE THREAD

**Issue by romans8** [tenable/integration-jira-cloud#84]
Platform: K8's, Tenable.sc

The Vulnerability tab pulled in all the required fields however the following is not populating in Jira:
Asset UUID
Device NetBIOS
Tenable Platform
Vulnerability Repository ID
Vulnerability Repository Name

**Comment by SteveMcGrath** [comment]
What version of Tenable.sc are you connecting to?  While there shouldnt be any breaking changes between versions, its easier to replicate if I have a like-for-like.

**Comment by SteveMcGrath** [comment]
I have just tested against the version of SC i have installed and everything appears to be working as expected.

**Comment by SteveMcGrath** [comment]
Also if you can provide the debug.md file of the last run, I can do some field marrying to see whats happening here.

**Comment by SteveMcGrath** [comment]
1.1.18 released.  If the issue continues, please comment and provide updated logs.  We may need to use the new dry_run feature within the config as well to root out the issue if it still exists.

No response by 1/1/21 will result in an auto-close.

**Comment by romans8** [comment]
Thanks
