### ISSUE TITLE
Asset Tags not importing from Tenable.io

### ISSUE THREAD

**Issue by patrickoneiltc** [tenable/integration-jira-cloud#85]
I cannot get Asset Tag data to populate from Tenable.io. All other relevant asset data (Host name, IP, Mac, etc, Host UUID) imports. running the connector with --troubleshoot provides "\"Tenable Asset Tags\" is EMPTY" for every host. The only other mention of asset tags (either as "asset tags" or "asset.tag"  anywhere in issue_debug.md is the mention that the customfield in Jira exists. I tried deleting the field, and in that case, the script creates it, but once again only outputs "\"Tenable Asset Tags\" is EMPTY". I can confirm that the field exists in Jira, and is in the same order for the ASSET screen as listed in config.py

Python version 3.6.9
Tenable Jira Connector version 1.1.17
Reporting configured for DEBUG

API keys for administrator account, JIRA user also Admin. Curled a host using the API keys, was able to return asset tag data.

If you'd like, I can send you the output of issue_debug.md over email, but it seems to lack in any relevant information.

Note: Originally, there was no asset tag information anywhere in the issue_debug.md file, other than the mention of of the custom field. I added the below to my config, and that returns that there is no value for "Tenable Asset Tags":
 ```
search:
      - Tenable Platform
      - Tenable Plugin ID
      - Tenable Asset Tags
      - Tenable Asset UUID
      - Device IPv4 Addresses
      - Device IPv6 Addresses
      - Vulnerability Port
      - Vulnerability Protocol
```

**Comment by SteveMcGrath** [comment]
I would highly recommend removing the Asset Tags (and the Device IPvX Addresses) from the search context.  This will create issues for asset matching between IO and Jira.

**Comment by SteveMcGrath** [comment]
Alright, so lets see whats happening here.  Can you please save the following script, run it, then paste the output into the issue?  You may need to modify the `config.yaml` to point to your config file.

```python
#!/usr/bin/env python
import yaml, json
from tenable_jira.config import base_config
from tenable.utils import dict_merge
from tenable.io import TenableIO

config = dict_merge(base_config(), yaml.load(open('config.yaml'), Loader=yaml.Loader))

tio = TenableIO(
    access_key=config['tenable'].get('access_key'),
    secret_key=config['tenable'].get('secret_key')
)

for asset in tio.exports.assets():
    print(asset['id'], ', '.join([f'{t["key"]}:{t["value"]}' for t in asset['tags']]))
```

**Comment by patrickoneiltc** [comment]
I will remove the "Tenable Asset Tags" and IP address stuff from the search list. I only added the asset tag line for troubleshooting. The IP address search fields are part of the default config.py. I am going to run the troubleshooting version of the script with those fields removed, in the off chance that it will help. 

The output from your script above is a UUID, then tag info. I'll post a couple, with the UUID redacted. 
```
REDACTED Windows:Windows_10, Windows Hosts:Windows
REDACTED AWS Agent Environment:PROD
REDACTED Mac Hosts:MacOS
```
On the first line, you'll see Windows mentioned twice. I created tags that had no spaces incase there was an issue in parsing spaces.

**Comment by SteveMcGrath** [comment]
if you search for those UUIDs, within Jira, they are empty?

**Comment by patrickoneiltc** [comment]
No results for 5 different searched UUIDs. However, I tagged my personal host for testing, and found that UUID value in a subtask for my host, and when I click on it, I get a list of subtasks for my host. Weird.
I didn't note it in my first post, but we are using Jira Cloud.

**Comment by SteveMcGrath** [comment]
what version of the integration are you using?

**Comment by patrickoneiltc** [comment]
1.1.17

**Comment by patrickoneiltc** [comment]
I appear to have answered your last question in error. I have 1.1.16 as the last entry in change log. Let me update and try this all over again.

**Comment by SteveMcGrath** [comment]
please update to 1.1.17 and try again.

**Comment by patrickoneiltc** [comment]
I switched my project to the actual branch I meant to work from, and redeployed. I completely replaced the involved host in the process. I can confirm that version 1.1.17 is running. Still, nothing about tags other than "2020-12-02 16:49:23,361 tenable_jira.jira.Jira INFO Tenable Asset Tags is customfield_11553 (existing)" When I run in --troubleshoot. As soon as this run is complete, I will email the debug file to you.

**Comment by patrickoneiltc** [comment]
I am trying to get clean results, with only recent findings, because of the massive size of the file and the run time. I cannot get the command ```tenable-jira -s $(date -v-1d +%s) config.yaml``` to work. `-v` is not a valid 'date' switch, and I cannot find anything in the manual that suggests another switch in it's place.

**Comment by SteveMcGrath** [comment]
1.1.17 introduces the age attribute which you can specify under the tenable stanza.

https://github.com/tenable/integration-jira-cloud/blob/master/tenable_jira/config.py#L50

**Comment by patrickoneiltc** [comment]
Debug file sent over via email.

**Comment by SteveMcGrath** [comment]
Continuing this conversation over email.  Will update issue once the source of the problem has been identified.

**Comment by SteveMcGrath** [comment]
1.1.18 released and should address this issue
