### ISSUE TITLE
If i want to connect both tenable.io and tenable.sc for 2 separate projects

### ISSUE THREAD

**Issue by valterebizh** [tenable/integration-jira-cloud#88]
Hey, 

QQ config says I can only connect either one, tenable.io or tenable.sc - how can I have a second config file on the same machine to connect to the other agent? Or would i need to use Docker or something of the like?

Kind Regards,

VT

**Comment by SteveMcGrath** [comment]
you can have multiple configs and call them.  you just cant run both at the same time.

**Comment by valterebizh** [comment]
got it thank you!
