### ISSUE TITLE
Configuring for a Jira Next-Gen Project

### ISSUE THREAD

**Issue by MikeBourgault** [tenable/integration-jira-cloud#9]
Hi Steven,

I've been testing this on a JIra Next-Gen Project and I'm relatively sure that it is not going to work after I work through the bugs (due to lack of screens), but I just wanted to bring forward my errors and see if this could potentially work.

I attempted to fill in config.py with `jira_id: <id_for_task>` for both task and subtask.

But I am receiving the error:
`restfly.errors.BadRequestError: [400: PUT] https://<orgid>.atlassian.net/rest/api/3/issue/61216?notifyUsers=true&overrideScreenSecurity=false&overrideEditableFlag=false body=b'{"errorMessages":[],"errors":{"issuetype":"The issue type selected is invalid."}}'`

Within my project, I have task and sub_task configured as issue types. Anything else you can think to try? or is this a no go? 

Thanks,
Mike

**Comment by SteveMcGrath** [comment]
This code is pinned to Jira Cloud's version 3 API.  It would likely require a significant recode to work with any Next-Gen projects.
