### ISSUE TITLE
Custom workflows and the integration

### ISSUE THREAD

**Issue by adrapps** [tenable/integration-jira-cloud#93]
Can custom Jira workflows be used with the integration? How is the below statement from https://github.com/tenable/integration-jira-cloud affected by a custom workflow?

- Vulnerability Instances (Sub-tasks) are closed automatically by the integration once the vulnerability is fixed in Tenable.io.
- Vulnerabilities (Tasks) are closed once all Sub-tasks enter a closed state.
- If a vulnerability is re-opened, new issue tickets are generated (The integration will not reopen previously closed issues (otherwise known as necromancy))

Thanks in advance!

**Comment by SteveMcGrath** [comment]
Assuming you dont do anything that would break the current behavior, i dont see any issue.  If you are looking to augment to support accepting the risk, I would suggest you add a new transition state that is outside the defaults.
