### ISSUE TITLE
Project has been created but no data being imported

### ISSUE THREAD

**Issue by Wilks1** [tenable/integration-jira-cloud#94]
Hi,

Just done the integration steps following the wiki.

I do not receive an error message when running tenable-jira config.yaml and it completes after around 30s to 1 min.

The script has created a VULN project, with 2 screens and I can see the custom fields have been created. However the custom fields are not associated to any screens?

Are you able to assist?

Please let me know any further details you require.

Thanks

**Comment by SteveMcGrath** [comment]
Have you looked at the common issues section of the readme?  https://github.com/tenable/integration-jira-cloud

**Comment by Wilks1** [comment]
Ah, I had looked at the two issues above but not for the no screens selected.

I am picking this up again tomorrow so will try specifying the screens tomorrow. Will update you and close if sucessful.

Thanks for the quick reply

**Comment by Wilks1** [comment]
This solved the issue - https://github.com/tenable/integration-jira-cloud/issues/23#issuecomment-604631753

Thanks for your help
