### ISSUE TITLE
CVSS Threshold ?

### ISSUE THREAD

**Issue by MichaelTay0** [tenable/integration-jira-cloud#95]
Similar to a previous issue of mine,

But I wanted to know if there is a feature to only created jira tasks and subtasks for CVSS scores over a specific threshold?

I'm guessing it would have to be some sort of edit to the config.yaml file

**Comment by SteveMcGrath** [comment]
severity has historically acted as that threshold.  The integration is currently limited by the export filtering capabilities by the API itself.  To go further would mean pulling more data and client-side filtering from there.

<4 = Low
>=4 && <7 = Medium
>=7 && <10 = High
10 = Critical

**Comment by MichaelTay0** [comment]
Thanks steve that makes sense. this can be closed
