### ISSUE TITLE
Tags with spaces get split by ingestor/Jira

### ISSUE THREAD

**Issue by jrmcpeek** [tenable/integration-jira-cloud#98]
As part of our Tenable.io set, we use a tag category of "Location" with values representing location, one of which is "New York".

When running this, the end result in Jira looks like:

![image](https://user-images.githubusercontent.com/55411348/107063915-8c3a6e80-67a0-11eb-91b5-aa52b790665c.png)

**Comment by Mooey28** [comment]
I was just coming to post the same issue, so commenting just for awareness. 

Thank you for having tags be included within the Jira ingest though, it's a massive positive in general.

**Comment by SteveMcGrath** [comment]
I think the best solution here is to add a replace to convert spaces into underscores.

**Comment by SteveMcGrath** [comment]
1.1.20 addresses this by replacing spaces with underscores.
