### ISSUE TITLE
Runs are hanging

### ISSUE THREAD

**Issue by adrappley** [tenable/integration-jira-cloud#99]
Hi Steve,

I've tried both a basic run and an "observed since" run and both are hanging. 'I've even let them run overnight. So I have to abort the run. I've run the --troubleshoot on it and checked the export status on https://developer.tenable.com/reference#exports-vulns-export-status with it showing as "FINISHED". Not sure if vuln data is being pushed accurately. 

Here's my issue_debug.md for reference.
[issue_debug.txt](https://github.com/tenable/integration-jira-cloud/files/5960652/issue_debug.txt)

Any ideas?

Appreciate the help.

**Comment by SteveMcGrath** [comment]
The debug indicates a successful run.

```
2021-02-10 10:00:08,351 tenable.io.TenableIO DEBUG Request-UUID 1453aa7b0d02062574c1c57b691bd0d9 for https://cloud.tenable.com/vulns/export/63d6514c-2e58-46a7-80c1-a6d985b67415/status
2021-02-10 10:00:08,352 tenable.io.exports.ExportsIterator DEBUG EXPORT vulns 63d6514c-2e58-46a7-80c1-a6d985b67415 is status FINISHED
```

You DO have the service interval set, which would tell the integration to run as a service and just sleep for that many hours and re-run the delta between the last run and current.

**Comment by SteveMcGrath** [comment]
closing due to lack of response.
